export const apiData = {"response_code":0,"results":[{"type":"multiple","difficulty":"easy","category":"Entertainment: Cartoon &amp; Animations","question":"What is the relationship between Rick and Morty in the show &quot;Rick and Morty&quot;?","correct_answer":"Grandfather and Grandson","incorrect_answers":["Father and Son","Best Friends","Crimefighting Partners"]},{"type":"multiple","difficulty":"easy","category":"Entertainment: Cartoon &amp; Animations","question":"Wendy O. Koopa appeared in the Super Mario DIC Cartoons, but what was she known as?","correct_answer":"Kootie Pie","incorrect_answers":["Sweetie Pie","Wendy Pie","Honey Pie"]},{"type":"multiple","difficulty":"hard","category":"Entertainment: Cartoon &amp; Animations","question":"Which of the following films was Don Bluth both the writer, director, and producer for?","correct_answer":"All Dogs Go To Heaven","incorrect_answers":["Titan A.E.","Anastasia","The Land Before Time"]},{"type":"multiple","difficulty":"easy","category":"Entertainment: Cartoon &amp; Animations","question":"Who created the Cartoon Network series &quot;Adventure Time&quot;?","correct_answer":"Pendleton Ward","incorrect_answers":["J. G. Quintel","Ben Bocquelet","Rebecca Sugar"]},{"type":"multiple","difficulty":"medium","category":"Entertainment: Cartoon &amp; Animations","question":"What was the number on Gerald&#039;s shirt in &quot;Hey Arnold!&quot;?","correct_answer":"33","incorrect_answers":["88","38","83"]},{"type":"multiple","difficulty":"easy","category":"Entertainment: Cartoon &amp; Animations","question":"What is Everest&#039;s favorite food in the Nickelodeon\/Nick Jr. series &quot;PAW Patrol&quot;?","correct_answer":"Liver","incorrect_answers":["Chicken","Steak","Caribou"]},{"type":"multiple","difficulty":"easy","category":"Entertainment: Cartoon &amp; Animations","question":"In the show &quot;Steven Universe&quot;, who are the main two employees of The Big Donut?","correct_answer":"Sadie and Lars","incorrect_answers":["Steven and James","Erik and Julie","Bob and May"]},{"type":"multiple","difficulty":"medium","category":"Entertainment: Cartoon &amp; Animations","question":"In &quot;The Amazing World of Gumball&quot;, who is the principal of Elmore Junior High?","correct_answer":"Principal Brown","incorrect_answers":["Principal Small","Principal Brawn","Principal Simeon"]},{"type":"multiple","difficulty":"easy","category":"Entertainment: Cartoon &amp; Animations","question":"Which of the following is not a Flintstones character?","correct_answer":"Lord Rockingham IX","incorrect_answers":["Rockhead Slate","The Great Gazoo","Barney Rubble"]},{"type":"multiple","difficulty":"medium","category":"Entertainment: Cartoon &amp; Animations","question":"What Cartoon Network show aired its first episode on November 4th, 2013?","correct_answer":"Steven Universe","incorrect_answers":["Regular Show","Adventure Time","The Amazing World of Gumball"]},{"type":"multiple","difficulty":"easy","category":"Entertainment: Cartoon &amp; Animations","question":"In the show &quot;Foster&#039;s Home For Imaginary Friends&quot;, which character had an obsession with basketball?","correct_answer":"Wilt","incorrect_answers":["Coco","Mac","Cheese"]},{"type":"multiple","difficulty":"medium","category":"Entertainment: Cartoon &amp; Animations","question":"Which episode from The Amazing World Of Gumball won the Childrens Choice Award at the British Animation Awards in 2016?","correct_answer":"The Shell","incorrect_answers":["The Limit","The Kids","The Gripes"]},{"type":"multiple","difficulty":"easy","category":"Entertainment: Cartoon &amp; Animations","question":"What is the name of the creatures that the protagonists of the webshow RWBY fight against?","correct_answer":"Grimm","incorrect_answers":["Reavers","Heartless","Dark Ones"]},{"type":"multiple","difficulty":"hard","category":"Entertainment: Cartoon &amp; Animations","question":"What was Maggie Simpson&#039;s first canonical word, not including the Tracey Ullman shorts?","correct_answer":"Daddy.","incorrect_answers":["Sequel?","Ja!","Rusty!"]},{"type":"multiple","difficulty":"hard","category":"Entertainment: Cartoon &amp; Animations","question":"In the 1969 Cartoon show &quot;Dastardly and Muttley in Their Flying Machines&quot;, which were NOT one of the lyrics in the opening theme?","correct_answer":"Stab him","incorrect_answers":["Nab him","Jab him","Tab him"]},{"type":"multiple","difficulty":"medium","category":"Entertainment: Cartoon &amp; Animations","question":"What is the name of the Alligator that The Simpsons &quot;killed&quot; in the episode &quot;Kill The Alligator and Run&quot;?","correct_answer":"Captain Jack","incorrect_answers":["Captain Jake","Captain Hector","Captain Flynn"]},{"type":"multiple","difficulty":"easy","category":"Entertainment: Cartoon &amp; Animations","question":"In the 1993 Disney animated series &quot;Bonkers&quot;, what is the name of Bonker&#039;s second partner?","correct_answer":"Miranda Wright","incorrect_answers":["Dick Tracy","Eddie Valiant","Dr. Ludwig von Drake"]},{"type":"multiple","difficulty":"easy","category":"Entertainment: Cartoon &amp; Animations","question":"What was the first Disney movie to use CGI?","correct_answer":"The Black Cauldron","incorrect_answers":["Tron","Toy Story","Fantasia"]},{"type":"multiple","difficulty":"medium","category":"Entertainment: Cartoon &amp; Animations","question":"In the Dreamworks animated movie &quot;Madagascar,&quot; who voices Maurice the lemur?","correct_answer":"Cedric the Entertainer","incorrect_answers":["Jack Black","Sacha Baron Cohen","Chris Rock"]},{"type":"multiple","difficulty":"hard","category":"Entertainment: Cartoon &amp; Animations","question":"Townsend Coleman provided the voice for which turtle in the original 1987 series of &quot;Teenage Mutant Ninja Turtles&quot;?","correct_answer":"Michelangelo","incorrect_answers":["Leonardo","Donatello","Raphael"]}]}

export const questions_M =[
  {
    "ID": 1,
    "Question": "Limnology is the study of which type of water bodies?",
    "CorrectOption": "Inland waters (fresh or saline, standing or running)",
    "OptionA": "Inland waters (fresh or saline, standing or running)",
    "OptionB": "Only oceans",
    "OptionC": "Glaciers exclusively",
    "OptionD": "Atmospheric vapor",
    "AnswerExplanation": "Limnology focuses on lakes, ponds, rivers, streams, wetlands, and other continental waters—not marine or atmospheric systems.",
    "Category": "Introduction"
  },
  {
    "ID": 2,
    "Question": "Which scientist is widely credited with the early development of limnology as a discipline?",
    "CorrectOption": "François-Alphonse Forel",
    "OptionA": "François-Alphonse Forel",
    "OptionB": "Charles Darwin",
    "OptionC": "Rachel Carson",
    "OptionD": "Jacques Cousteau",
    "AnswerExplanation": "Forel’s late-1800s work on Lake Geneva earned him the title “Father of Limnology.”",
    "Category": "History"
  },
  {
    "ID": 3,
    "Question": "The epilimnion of a lake is typically characterized by:",
    "CorrectOption": "Warm, well-oxygenated surface water",
    "OptionA": "Warm, well-oxygenated surface water",
    "OptionB": "Cold, low-oxygen deep water",
    "OptionC": "A rapid temperature decline",
    "OptionD": "Complete absence of light",
    "AnswerExplanation": "Sunlight warms the surface layer and wind mixing keeps it oxygen-rich.",
    "Category": "Physical Properties"
  },
  {
    "ID": 4,
    "Question": "Which term describes a lake that mixes from top to bottom once each year?",
    "CorrectOption": "Monomictic",
    "OptionA": "Monomictic",
    "OptionB": "Dimictic",
    "OptionC": "Polymictic",
    "OptionD": "Meromictic",
    "AnswerExplanation": "Monomictic lakes destratify and fully mix a single time annually, usually in winter (warm-monomictic) or summer (cold-monomictic).",
    "Category": "Physical Properties"
  },
  {
    "ID": 5,
    "Question": "In a typical dissolved-oxygen profile of an eutrophic lake during summer, the lowest oxygen is likely found:",
    "CorrectOption": "Near the sediment in the hypolimnion",
    "OptionA": "Near the sediment in the hypolimnion",
    "OptionB": "At the surface epilimnion",
    "OptionC": "Throughout the thermocline",
    "OptionD": "Uniformly at every depth",
    "AnswerExplanation": "Respiration and decomposition use up oxygen in the isolated, deep hypolimnion of eutrophic lakes.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 6,
    "Question": "Which nutrient most commonly limits algal growth in freshwater lakes?",
    "CorrectOption": "Phosphorus",
    "OptionA": "Phosphorus",
    "OptionB": "Sodium",
    "OptionC": "Calcium",
    "OptionD": "Silicon",
    "AnswerExplanation": "In many freshwaters, small phosphorus additions trigger large algal blooms, showing it is the limiting nutrient.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 7,
    "Question": "A secchi disk reading primarily estimates a lake's:",
    "CorrectOption": "Water transparency",
    "OptionA": "Water transparency",
    "OptionB": "Surface water temperature",
    "OptionC": "pH level",
    "OptionD": "Salinity",
    "AnswerExplanation": "The depth at which the disk disappears quantifies clarity and thus turbidity or color.",
    "Category": "Field Methods"
  },
  {
    "ID": 8,
    "Question": "Which watershed feature tends to increase surface runoff and reduce infiltration?",
    "CorrectOption": "High percentage of impervious surfaces",
    "OptionA": "High percentage of impervious surfaces",
    "OptionB": "Dense forest cover",
    "OptionC": "Gentle slopes with grassland",
    "OptionD": "Deep sandy soils",
    "AnswerExplanation": "Pavement and roofs prevent water from soaking in, causing faster, higher runoff peaks.",
    "Category": "Watershed"
  },
  {
    "ID": 9,
    "Question": "The term 'hyporheic zone' refers to:",
    "CorrectOption": "Subsurface region beneath and alongside a stream where groundwater and surface water mix",
    "OptionA": "Subsurface region beneath and alongside a stream where groundwater and surface water mix",
    "OptionB": "Open-water photic zone",
    "OptionC": "Deep lake sediments",
    "OptionD": "Evaporation layer at the air-water interface",
    "AnswerExplanation": "Water exchanges through porous sediments, affecting nutrients and temperature in streams.",
    "Category": "Hydrology"
  },
  {
    "ID": 10,
    "Question": "Which gas, produced under anoxic conditions in sediments, can contribute to greenhouse warming when released?",
    "CorrectOption": "Methane (CH₄)",
    "OptionA": "Methane (CH₄)",
    "OptionB": "Oxygen (O₂)",
    "OptionC": "Argon (Ar)",
    "OptionD": "Helium (He)",
    "AnswerExplanation": "Anaerobic decomposition yields methane, a potent greenhouse gas if it reaches the atmosphere.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 11,
    "Question": "Turbidity in lakes is commonly measured in:",
    "CorrectOption": "Nephelometric Turbidity Units (NTU)",
    "OptionA": "Nephelometric Turbidity Units (NTU)",
    "OptionB": "Degrees Celsius",
    "OptionC": "Milligrams per liter",
    "OptionD": "Meters per second",
    "AnswerExplanation": "Nephelometers quantify light scattering by suspended particles, reported in NTU.",
    "Category": "Field Methods"
  },
  {
    "ID": 12,
    "Question": "Which lake zone is defined by light levels too low for photosynthesis?",
    "CorrectOption": "Aphotic zone",
    "OptionA": "Aphotic zone",
    "OptionB": "Epilimnion",
    "OptionC": "Euphotic zone",
    "OptionD": "Metaliminion",
    "AnswerExplanation": "Below the compensation depth, respiration exceeds photosynthesis, creating an aphotic zone.",
    "Category": "Physical Properties"
  },
  {
    "ID": 13,
    "Question": "During summer stratification, the metalimnion is best described as:",
    "CorrectOption": "Layer with the steepest temperature gradient",
    "OptionA": "Layer with the steepest temperature gradient",
    "OptionB": "Most oxygenated layer",
    "OptionC": "Layer of maximum salinity",
    "OptionD": "Zone of total darkness",
    "AnswerExplanation": "Temperature drops rapidly through this middle layer, separating warm and cold water masses.",
    "Category": "Physical Properties"
  },
  {
    "ID": 14,
    "Question": "Which of the following is an example of a lotic ecosystem?",
    "CorrectOption": "A flowing river",
    "OptionA": "A flowing river",
    "OptionB": "A deep stratified lake",
    "OptionC": "An oxbow pond",
    "OptionD": "A saline playa",
    "AnswerExplanation": "Lotic systems are flowing waters—rivers, streams—where current shapes habitat.",
    "Category": "Introduction"
  },
  {
    "ID": 15,
    "Question": "Oligotrophic lakes typically exhibit which characteristic?",
    "CorrectOption": "High water clarity",
    "OptionA": "High water clarity",
    "OptionB": "Persistent algal blooms",
    "OptionC": "Low dissolved oxygen",
    "OptionD": "Thick organic sediments",
    "AnswerExplanation": "With low nutrients, algal biomass is low and water remains clear.",
    "Category": "Biological Properties"
  },
  {
    "ID": 16,
    "Question": "The volume of water passing a point in a stream per unit time is called:",
    "CorrectOption": "Discharge",
    "OptionA": "Discharge",
    "OptionB": "Baseflow",
    "OptionC": "Infiltration",
    "OptionD": "Evapotranspiration",
    "AnswerExplanation": "Discharge (m³ s⁻¹) integrates velocity across the cross-section.",
    "Category": "Hydrology"
  },
  {
    "ID": 17,
    "Question": "Which parameter directly affects the buoyancy of aquatic organisms?",
    "CorrectOption": "Water density",
    "OptionA": "Water density",
    "OptionB": "Turbidity",
    "OptionC": "Secchi depth",
    "OptionD": "Watershed slope",
    "AnswerExplanation": "Archimedes’ principle: density differences determine flotation versus sinking.",
    "Category": "Physical Properties"
  },
  {
    "ID": 18,
    "Question": "In a lake, the compensation depth is defined where:",
    "CorrectOption": "Photosynthesis equals respiration",
    "OptionA": "Photosynthesis equals respiration",
    "OptionB": "Temperature equals maximum density",
    "OptionC": "Salinity equals atmospheric average",
    "OptionD": "Wind mixing stops",
    "AnswerExplanation": "Net oxygen production is zero; above it autotrophs gain biomass, below they lose it.",
    "Category": "Biological Properties"
  },
  {
    "ID": 19,
    "Question": "Why does cold water hold more dissolved oxygen than warm water?",
    "CorrectOption": "Gas solubility increases as temperature decreases",
    "OptionA": "Gas solubility increases as temperature decreases",
    "OptionB": "Cold water has higher salinity",
    "OptionC": "Cold water forms stronger hydrogen bonds",
    "OptionD": "Turbulence is lower in cold water",
    "AnswerExplanation": "Henry’s law: cooler liquids dissolve gases more readily.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 20,
    "Question": "Which watershed characteristic most strongly influences peak storm runoff?",
    "CorrectOption": "Land slope steepness",
    "OptionA": "Land slope steepness",
    "OptionB": "Average soil pH",
    "OptionC": "Precipitation color",
    "OptionD": "Volume of groundwater springs",
    "AnswerExplanation": "Steep slopes accelerate overland flow, raising peak discharge.",
    "Category": "Watershed"
  },
  {
    "ID": 21,
    "Question": "A meromictic lake is distinguished by:",
    "CorrectOption": "Permanent partial mixing with a non-mixing deep layer",
    "OptionA": "Permanent partial mixing with a non-mixing deep layer",
    "OptionB": "Complete mixing daily",
    "OptionC": "Mixing only during winter",
    "OptionD": "No thermocline formation at all",
    "AnswerExplanation": "Dense, saline bottom water never mixes with upper layers, forming a chemocline.",
    "Category": "Physical Properties"
  },
  {
    "ID": 22,
    "Question": "What term describes the nutrient-enriched water (often at inflow points) that can trigger algal blooms?",
    "CorrectOption": "Eutrophication",
    "OptionA": "Eutrophication",
    "OptionB": "Sedimentation",
    "OptionC": "Desalinization",
    "OptionD": "Calcification",
    "AnswerExplanation": "External nutrient loading accelerates ecosystem aging, termed cultural eutrophication.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 23,
    "Question": "Specific conductance in freshwater is mainly used as a proxy for:",
    "CorrectOption": "Total dissolved ions",
    "OptionA": "Total dissolved ions",
    "OptionB": "Thermal stratification",
    "OptionC": "Chlorophyll-a concentration",
    "OptionD": "Sediment grain size",
    "AnswerExplanation": "Ions carry electric current; higher ion content yields higher conductivity.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 24,
    "Question": "Which of the following is a renewable internal source of phosphorus in lakes?",
    "CorrectOption": "Release from anoxic sediments",
    "OptionA": "Release from anoxic sediments",
    "OptionB": "Atmospheric nitrogen fixation",
    "OptionC": "Acid rain",
    "OptionD": "Wind erosion from deserts",
    "AnswerExplanation": "Low redox in sediments dissolves iron-bound P, recycling it to the water column.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 25,
    "Question": "The volume of water stored in a lake divided by the outflow rate gives the lake’s:",
    "CorrectOption": "Water residence time",
    "OptionA": "Water residence time",
    "OptionB": "Secchi depth",
    "OptionC": "Hydraulic conductivity",
    "OptionD": "Saturation index",
    "AnswerExplanation": "Residence time (turnover time) indicates how long water, nutrients, or pollutants stay.",
    "Category": "Hydrology"
  },
  {
    "ID": 26,
    "Question": "Which physical property of water enables thermal stratification in lakes?",
    "CorrectOption": "Maximum density at 4 °C",
    "OptionA": "Maximum density at 4 °C",
    "OptionB": "High vapor pressure",
    "OptionC": "Low surface tension",
    "OptionD": "Compressibility",
    "AnswerExplanation": "Density decreases both above and below 4 °C, allowing lighter warm and cold layers to float.",
    "Category": "Physical Properties"
  },
  {
    "ID": 27,
    "Question": "Settling velocity of suspended particles in water is increased by:",
    "CorrectOption": "Greater particle diameter",
    "OptionA": "Greater particle diameter",
    "OptionB": "Lower gravity",
    "OptionC": "Higher turbulent flow",
    "OptionD": "Electrostatic repulsion",
    "AnswerExplanation": "Stokes’ law: settling speed rises with the square of particle radius.",
    "Category": "Physical Properties"
  },
  {
    "ID": 28,
    "Question": "Fluorometry is commonly used in limnology for measuring:",
    "CorrectOption": "Chlorophyll-a concentration",
    "OptionA": "Chlorophyll-a concentration",
    "OptionB": "Total hardness",
    "OptionC": "Dissolved potassium",
    "OptionD": "Sediment porosity",
    "AnswerExplanation": "Chlorophyll-a fluoresces; its signal is proportional to algal biomass.",
    "Category": "Field Methods"
  },
  {
    "ID": 29,
    "Question": "A primary function of wetlands in a watershed is to:",
    "CorrectOption": "Attenuate floods by storing water",
    "OptionA": "Attenuate floods by storing water",
    "OptionB": "Increase groundwater salinity",
    "OptionC": "Accelerate urban runoff",
    "OptionD": "Remove all nitrates instantly",
    "AnswerExplanation": "Wetland storage slows runoff peaks, reducing downstream flood risk.",
    "Category": "Watershed"
  },
  {
    "ID": 30,
    "Question": "Which gas exchange process is enhanced by wind-induced surface turbulence?",
    "CorrectOption": "Oxygen diffusion from atmosphere to water",
    "OptionA": "Oxygen diffusion from atmosphere to water",
    "OptionB": "CO₂ respired by sediments",
    "OptionC": "Methane oxidation in deep water",
    "OptionD": "Nitrogen fixation in macrophytes",
    "AnswerExplanation": "Wind increases boundary-layer mixing, boosting O₂ transfer into surface waters.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 31,
    "Question": "Cyanobacteria are often dominant in lakes with:",
    "CorrectOption": "High phosphorus and warm temperatures",
    "OptionA": "High phosphorus and warm temperatures",
    "OptionB": "Low pH and low temperature",
    "OptionC": "High salinity with no nutrients",
    "OptionD": "Very high transparency and cold water",
    "AnswerExplanation": "Cyanobacteria thrive in nutrient-rich, warm, stable conditions and can out-compete other algae.",
    "Category": "Biological Properties"
  },
  {
    "ID": 32,
    "Question": "Which ratio best predicts trophic status: Total Nitrogen to Total Phosphorus (TN:TP) values below __ are considered phosphorus-limited?",
    "CorrectOption": "13:1",
    "OptionA": "13:1",
    "OptionB": "50:1",
    "OptionC": "100:1",
    "OptionD": "200:1",
    "AnswerExplanation": "Below ~13, P is limiting; above ~20, N may limit; Redfield (16) is the classic benchmark.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 33,
    "Question": "The process by which dense, saline water sinks and becomes trapped at a lake bottom is termed:",
    "CorrectOption": "Chemocline formation",
    "OptionA": "Chemocline formation",
    "OptionB": "Evaporation inversion",
    "OptionC": "Seiche oscillation",
    "OptionD": "Dilution plume",
    "AnswerExplanation": "A chemocline separates saline monimolimnion from fresher mixolimnion in meromictic lakes.",
    "Category": "Physical Properties"
  },
  {
    "ID": 34,
    "Question": "Which instrument directly measures water column temperature at multiple depths?",
    "CorrectOption": "Thermistor chain",
    "OptionA": "Thermistor chain",
    "OptionB": "Secchi disk",
    "OptionC": "Hydride generator",
    "OptionD": "Current meter",
    "AnswerExplanation": "A vertical cable of thermistors logs temperature profiles over time.",
    "Category": "Field Methods"
  },
  {
    "ID": 35,
    "Question": "Lake turnover typically occurs in temperate dimictic lakes during:",
    "CorrectOption": "Spring and autumn",
    "OptionA": "Spring and autumn",
    "OptionB": "Mid-summer only",
    "OptionC": "Mid-winter only",
    "OptionD": "Every month",
    "AnswerExplanation": "When surface water cools to 4 °C, density equalizes and wind mixes the whole lake.",
    "Category": "Physical Properties"
  },
  {
    "ID": 36,
    "Question": "Which particle size class settles quickest in calm lake water?",
    "CorrectOption": "Sand (>0.062 mm)",
    "OptionA": "Sand (>0.062 mm)",
    "OptionB": "Silt (0.004-0.062 mm)",
    "OptionC": "Clay (<0.004 mm)",
    "OptionD": "Colloids (<0.001 mm)",
    "AnswerExplanation": "Larger, heavier sand grains experience greater gravitational settling velocity.",
    "Category": "Physical Properties"
  },
  {
    "ID": 37,
    "Question": "Allochthonous organic matter in a lake originates from:",
    "CorrectOption": "Outside the aquatic system (e.g., leaf litter)",
    "OptionA": "Outside the aquatic system (e.g., leaf litter)",
    "OptionB": "Phytoplankton within the lake",
    "OptionC": "Periphyton on sediments",
    "OptionD": "Autochthonous bacteria only",
    "AnswerExplanation": "Allochthonous inputs are external—terrestrial plant debris, soil, etc.",
    "Category": "Biological Properties"
  },
  {
    "ID": 38,
    "Question": "Which physical process can cause internal waves within a stratified lake?",
    "CorrectOption": "Seiche",
    "OptionA": "Seiche",
    "OptionB": "Coriolis effect only",
    "OptionC": "Evaporation",
    "OptionD": "Photosynthesis",
    "AnswerExplanation": "A seiche sloshes water back and forth, tilting the thermocline like a see-saw.",
    "Category": "Physical Properties"
  },
  {
    "ID": 39,
    "Question": "High water color (humic substances) in dystrophic lakes _____ penetration of UV light:",
    "CorrectOption": "Reduces",
    "OptionA": "Reduces",
    "OptionB": "Enhances",
    "OptionC": "Has no effect on",
    "OptionD": "Totally eliminates",
    "AnswerExplanation": "Colored dissolved organic matter strongly absorbs UV and visible light.",
    "Category": "Physical Properties"
  },
  {
    "ID": 40,
    "Question": "The process of nitrogen gas (N₂) conversion into ammonia by cyanobacteria is called:",
    "CorrectOption": "Biological nitrogen fixation",
    "OptionA": "Biological nitrogen fixation",
    "OptionB": "Denitrification",
    "OptionC": "Nitrification",
    "OptionD": "Ammonification",
    "AnswerExplanation": "Nitrogenase enzyme in heterocysts reduces N₂ to NH₃, adding usable N to ecosystems.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 41,
    "Question": "Acidification of lakes can lead to loss of fish populations primarily because:",
    "CorrectOption": "Low pH mobilizes toxic aluminum",
    "OptionA": "Low pH mobilizes toxic aluminum",
    "OptionB": "High alkalinity dissolves oxygen",
    "OptionC": "CO₂ becomes insoluble",
    "OptionD": "Carbonate sediments increase",
    "AnswerExplanation": "Mobilized Al damages fish gills and eggs; pH<5 often critical.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 42,
    "Question": "Residence time in a reservoir is calculated from volume divided by:",
    "CorrectOption": "Outflow rate",
    "OptionA": "Outflow rate",
    "OptionB": "Evaporation rate",
    "OptionC": "Precipitation depth",
    "OptionD": "Catchment area",
    "AnswerExplanation": "It’s an average stay (turnover) time of water mass before leaving the reservoir.",
    "Category": "Hydrology"
  },
  {
    "ID": 43,
    "Question": "Diel vertical migration of zooplankton is thought to be primarily an adaptation to:",
    "CorrectOption": "Avoid visual predators during daylight",
    "OptionA": "Avoid visual predators during daylight",
    "OptionB": "Increase nutrient uptake",
    "OptionC": "Gain oxygen at depth",
    "OptionD": "Conserve body water",
    "AnswerExplanation": "Plankton hide in deep dark water by day, feed near surface at night.",
    "Category": "Biological Properties"
  },
  {
    "ID": 44,
    "Question": "Which form of phosphorus is directly taken up by algae?",
    "CorrectOption": "Orthophosphate (PO₄³⁻)",
    "OptionA": "Orthophosphate (PO₄³⁻)",
    "OptionB": "Particulate organic phosphorus",
    "OptionC": "Polyphosphate chains",
    "OptionD": "Chelated phosphorus",
    "AnswerExplanation": "Algae absorb soluble reactive P, mainly as orthophosphate ions.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 45,
    "Question": "A polymictic lake mixes:",
    "CorrectOption": "Many times per year or continuously",
    "OptionA": "Many times per year or continuously",
    "OptionB": "Only once every decade",
    "OptionC": "Only under ice cover",
    "OptionD": "Never (permanently stratified)",
    "AnswerExplanation": "Shallow tropical or wind-exposed lakes often stratify weakly and mix often.",
    "Category": "Physical Properties"
  },
  {
    "ID": 46,
    "Question": "The rate at which algae produce oxygen in the light minus the oxygen consumed in the dark gives:",
    "CorrectOption": "Net primary productivity",
    "OptionA": "Net primary productivity",
    "OptionB": "Gross primary productivity",
    "OptionC": "Respiration rate",
    "OptionD": "Photosynthetic quotient",
    "AnswerExplanation": "Net = gross photosynthesis minus respiration, measuring biomass gain.",
    "Category": "Biological Properties"
  },
  {
    "ID": 47,
    "Question": "Sediment core dating using ²¹⁰Pb radioisotope typically provides ages up to:",
    "CorrectOption": "About 100-150 years",
    "OptionA": "About 100-150 years",
    "OptionB": "1,000 years",
    "OptionC": "10,000 years",
    "OptionD": "No practical limit",
    "AnswerExplanation": "210Pb half-life (22 yr) is useful for recent sedimentation records ~5-7 half-lives.",
    "Category": "Field Methods"
  },
  {
    "ID": 48,
    "Question": "Macrophytes in littoral zones provide the following benefit:",
    "CorrectOption": "Habitat structure for fish and invertebrates",
    "OptionA": "Habitat structure for fish and invertebrates",
    "OptionB": "Reduction in primary production",
    "OptionC": "Increase in sediment resuspension",
    "OptionD": "Elimination of periphyton",
    "AnswerExplanation": "Physical complexity and refuge among stems enhance biodiversity.",
    "Category": "Biological Properties"
  },
  {
    "ID": 49,
    "Question": "A lake formed by glacial scouring and moraine dams is called a:",
    "CorrectOption": "Glacial lake",
    "OptionA": "Glacial lake",
    "OptionB": "Tectonic lake",
    "OptionC": "Volcanic caldera lake",
    "OptionD": "Solution lake",
    "AnswerExplanation": "Most northern temperate lakes owe their basins to glacial erosion/deposition.",
    "Category": "Formation"
  },
  {
    "ID": 50,
    "Question": "Which equation estimates theoretical evaporation under ideal conditions?",
    "CorrectOption": "Dalton’s law of evaporation",
    "OptionA": "Dalton’s law of evaporation",
    "OptionB": "Henry’s law",
    "OptionC": "Fick’s law",
    "OptionD": "Beer–Lambert law",
    "AnswerExplanation": "Dalton related evaporation rate to vapor pressure deficit and wind speed.",
    "Category": "Hydrology"
  },
  {
    "ID": 51,
    "Question": "Heterotrophic bacteria in lakes play a critical role in:",
    "CorrectOption": "Decomposition of organic matter",
    "OptionA": "Decomposition of organic matter",
    "OptionB": "Fixing atmospheric nitrogen only",
    "OptionC": "Reducing heavy metals to solids",
    "OptionD": "Generating internal seiches",
    "AnswerExplanation": "They mineralize organic carbon, recycling nutrients back into the food web.",
    "Category": "Biological Properties"
  },
  {
    "ID": 52,
    "Question": "Which sensor would you use to continuously record surface irradiance at a lake?",
    "CorrectOption": "Pyranometer",
    "OptionA": "Pyranometer",
    "OptionB": "Fluorometer",
    "OptionC": "Refractometer",
    "OptionD": "Secchi disk",
    "AnswerExplanation": "A pyranometer measures total solar radiation flux density (W m⁻²).",
    "Category": "Field Methods"
  },
  {
    "ID": 53,
    "Question": "An increase in alkalinity generally indicates a greater capacity to:",
    "CorrectOption": "Buffer pH changes",
    "OptionA": "Buffer pH changes",
    "OptionB": "Lower conductivity",
    "OptionC": "Increase turbidity",
    "OptionD": "Accelerate stratification",
    "AnswerExplanation": "Bicarbonate and carbonate ions neutralize acids, stabilizing pH.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 54,
    "Question": "Which isotopic ratio is widely used to study groundwater-lake interactions?",
    "CorrectOption": "⁸⁷Sr/⁸⁶Sr",
    "OptionA": "⁸⁷Sr/⁸⁶Sr",
    "OptionB": "¹⁴C/¹²C",
    "OptionC": "²⁰⁶Pb/²⁰⁴Pb",
    "OptionD": "³H/³He",
    "AnswerExplanation": "Different rock types impart distinctive Sr signatures to groundwater entering lakes.",
    "Category": "Hydrology"
  },
  {
    "ID": 55,
    "Question": "The 'Allometry' concept in plankton ecology relates cell size to:",
    "CorrectOption": "Physiological rates such as growth or respiration",
    "OptionA": "Physiological rates such as growth or respiration",
    "OptionB": "Streamflow velocity",
    "OptionC": "Watershed slope",
    "OptionD": "Dissolved silica",
    "AnswerExplanation": "Metabolic rate scales predictably with organism size via allometric equations.",
    "Category": "Biological Properties"
  },
  {
    "ID": 56,
    "Question": "A river reach with alternating deep pools and shallow riffles is best described as:",
    "CorrectOption": "Pool-riffle sequence",
    "OptionA": "Pool-riffle sequence",
    "OptionB": "Braided channel",
    "OptionC": "Straight thalweg",
    "OptionD": "Dendritic drainage",
    "AnswerExplanation": "Pool-riffle morphology is common in gravel-bed streams and enhances habitat diversity.",
    "Category": "Hydrology"
  },
  {
    "ID": 57,
    "Question": "Which of the following reduces the likelihood of algal blooms?",
    "CorrectOption": "Reducing nutrient inputs (P and N)",
    "OptionA": "Reducing nutrient inputs (P and N)",
    "OptionB": "Increasing sediment resuspension",
    "OptionC": "Adding fish predators",
    "OptionD": "Lowering water clarity",
    "AnswerExplanation": "Cutting external nutrient sources is the primary control on excessive algal growth.",
    "Category": "Management"
  },
  {
    "ID": 58,
    "Question": "The primary pigment used by algae for photosynthesis is:",
    "CorrectOption": "Chlorophyll-a",
    "OptionA": "Chlorophyll-a",
    "OptionB": "Xanthophyll",
    "OptionC": "Phycocyanin",
    "OptionD": "Carotene",
    "AnswerExplanation": "Chlorophyll-a absorbs red/blue light, driving light reactions of photosynthesis.",
    "Category": "Biological Properties"
  },
  {
    "ID": 59,
    "Question": "Which hydrologic process returns the largest volume of water back to the atmosphere from land?",
    "CorrectOption": "Evapotranspiration",
    "OptionA": "Evapotranspiration",
    "OptionB": "Infiltration",
    "OptionC": "Runoff",
    "OptionD": "Percolation",
    "AnswerExplanation": "Combined evaporation and plant transpiration dominate terrestrial water loss.",
    "Category": "Hydrology"
  },
  {
    "ID": 60,
    "Question": "Which method is commonly used to estimate gross primary production in lakes via oxygen changes?",
    "CorrectOption": "Light-and-dark bottle method",
    "OptionA": "Light-and-dark bottle method",
    "OptionB": "Secchi depth attenuation",
    "OptionC": "Evaporation pan",
    "OptionD": "Gravimetric filtration",
    "AnswerExplanation": "O₂ produced in light minus O₂ in dark bottles yields gross and net production.",
    "Category": "Field Methods"
  },
  {
    "ID": 61,
    "Question": "Large woody debris in streams generally:",
    "CorrectOption": "Creates habitat complexity and slows flow",
    "OptionA": "Creates habitat complexity and slows flow",
    "OptionB": "Eliminates hyporheic exchange",
    "OptionC": "Reduces dissolved oxygen",
    "OptionD": "Increases water temperature",
    "AnswerExplanation": "Logs form pools, trap sediment, and provide cover for aquatic life.",
    "Category": "Hydrology"
  },
  {
    "ID": 62,
    "Question": "The term 'metalimnetic oxygen maximum' refers to elevated DO at the thermocline due to:",
    "CorrectOption": "Photosynthesis by phytoplankton concentrated at that depth",
    "OptionA": "Photosynthesis by phytoplankton concentrated at that depth",
    "OptionB": "Groundwater upwelling",
    "OptionC": "Oxygen from sediments diffusing upward",
    "OptionD": "Gas supersaturation from ice melt",
    "AnswerExplanation": "Algae accumulate at the light-nutrient balance depth, producing excess O₂.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 63,
    "Question": "Photic depth often defined as 1% surface light is roughly equal to _____ times secchi depth in clear lakes.",
    "CorrectOption": "2.5-3",
    "OptionA": "2.5-3",
    "OptionB": "1",
    "OptionC": "5-6",
    "OptionD": "10",
    "AnswerExplanation": "Empirical studies show euphotic depth ≈ 2.7× Secchi in low-color waters.",
    "Category": "Physical Properties"
  },
  {
    "ID": 64,
    "Question": "The Coriolis effect causes large lake currents in the Northern Hemisphere to deflect:",
    "CorrectOption": "To the right of the wind direction",
    "OptionA": "To the right of the wind direction",
    "OptionB": "To the left of the wind direction",
    "OptionC": "Straight downward",
    "OptionD": "Has no effect on lakes",
    "AnswerExplanation": "Earth’s rotation deflects moving water rightward north of the equator.",
    "Category": "Physical Properties"
  },
  {
    "ID": 65,
    "Question": "Biomanipulation to control algal blooms often involves stocking:",
    "CorrectOption": "Piscivorous fish to reduce planktivores",
    "OptionA": "Piscivorous fish to reduce planktivores",
    "OptionB": "Herbivorous fish to graze macrophytes",
    "OptionC": "Benthic feeders to stir sediments",
    "OptionD": "Mosquito larvae to consume algae",
    "AnswerExplanation": "Top-down control: fewer planktivores → more zooplankton grazers → less algae.",
    "Category": "Management"
  },
  {
    "ID": 66,
    "Question": "Which of the following best describes bankfull discharge?",
    "CorrectOption": "Flow that fills the channel and just begins to spill onto the floodplain",
    "OptionA": "Flow that fills the channel and just begins to spill onto the floodplain",
    "OptionB": "Lowest flow in a 10-year drought",
    "OptionC": "Discharge during the 100-year flood",
    "OptionD": "Flow velocity at the thalweg",
    "AnswerExplanation": "Geomorphically effective flow shaping the channel occurs near bankfull.",
    "Category": "Hydrology"
  },
  {
    "ID": 67,
    "Question": "Littoral zones often have higher biodiversity because of:",
    "CorrectOption": "Structural complexity from macrophytes",
    "OptionA": "Structural complexity from macrophytes",
    "OptionB": "Low light and low oxygen",
    "OptionC": "An absence of predators",
    "OptionD": "Lower nutrient levels",
    "AnswerExplanation": "Vegetation, substrate diversity, and light create many niches for organisms.",
    "Category": "Biological Properties"
  },
  {
    "ID": 68,
    "Question": "Which component of the hydrologic cycle directly contributes to groundwater recharge?",
    "CorrectOption": "Infiltration through soil",
    "OptionA": "Infiltration through soil",
    "OptionB": "Canopy interception",
    "OptionC": "Evapotranspiration",
    "OptionD": "Surface runoff",
    "AnswerExplanation": "Water percolates downward, replenishing aquifers that later feed springs.",
    "Category": "Hydrology"
  },
  {
    "ID": 69,
    "Question": "Reduced mixing due to strong thermal stratification can lead to hypolimnetic:",
    "CorrectOption": "Oxygen depletion",
    "OptionA": "Oxygen depletion",
    "OptionB": "High transparency",
    "OptionC": "Temperature increase",
    "OptionD": "Phytoplankton blooms",
    "AnswerExplanation": "Isolation from atmosphere and respiration of settling organics consume O₂.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 70,
    "Question": "Which of the following best explains a seiche event?",
    "CorrectOption": "Standing oscillation of lake water caused by wind or pressure changes",
    "OptionA": "Standing oscillation of lake water caused by wind or pressure changes",
    "OptionB": "Vibrations in sediments from earthquakes",
    "OptionC": "Ice sheet expansion and contraction",
    "OptionD": "Internal production of methane bubbles",
    "AnswerExplanation": "Wind pushes water to one side; when wind stops, the water sloshes back and forth.",
    "Category": "Physical Properties"
  },
  {
    "ID": 71,
    "Question": "The Redfield ratio of 106:16:1 refers to the atomic ratio of:",
    "CorrectOption": "C:N:P in phytoplankton",
    "OptionA": "C:N:P in phytoplankton",
    "OptionB": "Na:K:Mg in seawater",
    "OptionC": "Fe:Mn:Cu in sediments",
    "OptionD": "H:O:Si in diatoms",
    "AnswerExplanation": "Marine and freshwater plankton average these elemental proportions in biomass.",
    "Category": "Biological Properties"
  },
  {
    "ID": 72,
    "Question": "A lake with high electrical conductivity likely indicates:",
    "CorrectOption": "High concentration of dissolved ions",
    "OptionA": "High concentration of dissolved ions",
    "OptionB": "Low nutrient status",
    "OptionC": "High dissolved oxygen",
    "OptionD": "Low total dissolved solids",
    "AnswerExplanation": "Conductivity is directly proportional to ionic strength of the water.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 73,
    "Question": "Which equation is used to model light attenuation with depth in water?",
    "CorrectOption": "Beer–Lambert law",
    "OptionA": "Beer–Lambert law",
    "OptionB": "Stokes law",
    "OptionC": "Reynolds number",
    "OptionD": "Poiseuille equation",
    "AnswerExplanation": "Light intensity decreases exponentially: I(z)=I₀e^(-kz).",
    "Category": "Physical Properties"
  },
  {
    "ID": 74,
    "Question": "Which macronutrient element is essential for ATP and DNA in aquatic organisms?",
    "CorrectOption": "Phosphorus",
    "OptionA": "Phosphorus",
    "OptionB": "Chloride",
    "OptionC": "Sulfate",
    "OptionD": "Argon",
    "AnswerExplanation": "Phosphorus forms the backbone of ATP, DNA, and phospholipids.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 75,
    "Question": "Calcite precipitation (whiting events) in lakes typically occurs when:",
    "CorrectOption": "Photosynthesis raises pH and causes CaCO₃ to precipitate",
    "OptionA": "Photosynthesis raises pH and causes CaCO₃ to precipitate",
    "OptionB": "Respiration lowers pH and dissolves CaCO₃",
    "OptionC": "CO₂ is injected into water",
    "OptionD": "Sulfur bacteria oxidize pyrite",
    "AnswerExplanation": "Removal of CO₂ during photosynthesis shifts carbonate equilibrium, precipitating CaCO₃.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 76,
    "Question": "Invasive zebra mussels often alter lake ecosystems by:",
    "CorrectOption": "Increasing water clarity through filter feeding",
    "OptionA": "Increasing water clarity through filter feeding",
    "OptionB": "Producing cyanotoxins",
    "OptionC": "Raising water temperature",
    "OptionD": "Decreasing calcium concentration",
    "AnswerExplanation": "They remove particles, clearing water, which can shift algal and macrophyte dynamics.",
    "Category": "Biological Properties"
  },
  {
    "ID": 77,
    "Question": "A stream reach dominated by fine sediments and low gradient likely supports which habitat type?",
    "CorrectOption": "Sand-bed glide habitat",
    "OptionA": "Sand-bed glide habitat",
    "OptionB": "Cobble riffle habitat",
    "OptionC": "Bedrock cascade",
    "OptionD": "Boulder rapid",
    "AnswerExplanation": "Low slope streams deposit sand, forming slow glides rather than riffles.",
    "Category": "Hydrology"
  },
  {
    "ID": 78,
    "Question": "Which lake measurement technique directly estimates total primary production under natural light?",
    "CorrectOption": "Diurnal dissolved-oxygen curve method",
    "OptionA": "Diurnal dissolved-oxygen curve method",
    "OptionB": "Light-dark bottle incubation only",
    "OptionC": "Secchi depth conversion",
    "OptionD": "GIS shoreline mapping",
    "AnswerExplanation": "Tracking whole-lake O₂ change over 24 h integrates photosynthesis and respiration.",
    "Category": "Field Methods"
  },
  {
    "ID": 79,
    "Question": "The ratio of lake shoreline length to the circumference of a circle with equal area is called:",
    "CorrectOption": "Shoreline development index",
    "OptionA": "Shoreline development index",
    "OptionB": "Fetch ratio",
    "OptionC": "Volume development index",
    "OptionD": "Secchi coefficient",
    "AnswerExplanation": "This index indicates shoreline complexity; higher values mean more irregular shore.",
    "Category": "Physical Properties"
  },
  {
    "ID": 80,
    "Question": "Which of the following actions best mitigates cultural eutrophication?",
    "CorrectOption": "Reducing phosphorus inputs from wastewater",
    "OptionA": "Reducing phosphorus inputs from wastewater",
    "OptionB": "Increasing dredging frequency",
    "OptionC": "Lowering lake level each spring",
    "OptionD": "Adding urea-N fertilizer to stimulate algae",
    "AnswerExplanation": "Cutting point-source P is the most effective, long-term eutrophication control.",
    "Category": "Management"
  }
]

export const csc413 = [
  // --- Existing 30 Questions (from previous response) ---
  { ID: 1, Question: "What is the primary role of a translator in compiler design?", CorrectOption: "B", OptionA: "Execute source code", OptionB: "Convert source code to target language", OptionC: "Optimize assembly code", OptionD: "Debug source code", AnswerExplanation: "Translators convert a program in one language into another language that a computer can execute.", Category: "Introduction to Compilers" },
  { ID: 2, Question: "Which of these is NOT a translator type?", CorrectOption: "D", OptionA: "Compiler", OptionB: "Interpreter", OptionC: "Assembler", OptionD: "Debugger", AnswerExplanation: "Debugger is a tool for finding bugs, not a translator.", Category: "Introduction to Compilers" },
  { ID: 3, Question: "How does an interpreter differ from a compiler?", CorrectOption: "C", OptionA: "It translates the entire source code at once.", OptionB: "It always produces machine code.", OptionC: "It executes source code line-by-line.", OptionD: "It creates object files.", AnswerExplanation: "An interpreter executes the source code statement by statement without producing an object file.", Category: "Compilers vs Interpreters" },
  { ID: 4, Question: "Which language is closest to machine language?", CorrectOption: "C", OptionA: "High-level language", OptionB: "Assembly language", OptionC: "Machine language", OptionD: "Object-oriented language", AnswerExplanation: "Machine language is binary code directly understood by the computer hardware.", Category: "Programming Languages" },
  { ID: 5, Question: "What is lexical analysis responsible for in the compilation process?", CorrectOption: "D", OptionA: "Generating intermediate code", OptionB: "Checking syntax", OptionC: "Code optimization", OptionD: "Breaking input into tokens", AnswerExplanation: "Lexical analysis breaks input text into tokens like identifiers and literals.", Category: "Lexical Analysis" },
  { ID: 6, Question: "What does an assembler do?", CorrectOption: "B", OptionA: "Converts high-level code to machine code", OptionB: "Converts assembly code to machine code", OptionC: "Parses high-level code", OptionD: "Interprets source code", AnswerExplanation: "An assembler translates assembly language into machine language.", Category: "Translators" },
  { ID: 7, Question: "What is the main task of a linker?", CorrectOption: "C", OptionA: "Translate source code", OptionB: "Load executable programs", OptionC: "Combine object files into an executable", OptionD: "Check syntax errors", AnswerExplanation: "Linkers merge compiled object files into one executable.", Category: "System Programs" },
  { ID: 8, Question: "Which phase comes immediately after lexical analysis?", CorrectOption: "A", OptionA: "Syntax analysis", OptionB: "Semantic analysis", OptionC: "Code generation", OptionD: "Optimization", AnswerExplanation: "Syntax analysis parses tokens into a syntactic structure.", Category: "Compilation Process" },
  { ID: 9, Question: "What does 'source text' refer to in compiler design?", CorrectOption: "D", OptionA: "Target machine code", OptionB: "Optimized code", OptionC: "Binary executable", OptionD: "Original program code", AnswerExplanation: "Source text is the original program written in a programming language.", Category: "Basic Concepts" },
  { ID: 10, Question: "High-level programming languages are:", CorrectOption: "B", OptionA: "Written in binary digits", OptionB: "Human-friendly and easy to write", OptionC: "Assembly mnemonics", OptionD: "Low-level languages", AnswerExplanation: "High-level languages resemble natural language, making programming easier.", Category: "Programming Languages" },
  { ID: 11, Question: "Which phase verifies type compatibility in source code?", CorrectOption: "B", OptionA: "Syntax analysis", OptionB: "Semantic analysis", OptionC: "Lexical analysis", OptionD: "Code optimization", AnswerExplanation: "Semantic analysis checks if operators and operands have compatible types.", Category: "Semantic Analysis" },
  { ID: 12, Question: "What is operator precedence grammar useful for?", CorrectOption: "C", OptionA: "Defining lexical tokens", OptionB: "Optimizing code speed", OptionC: "Defining operator hierarchy in syntax", OptionD: "Code generation", AnswerExplanation: "Operator precedence grammar defines parsing rules based on operator precedence.", Category: "Grammar Types" },
  { ID: 13, Question: "Which automaton is commonly used to represent regular expressions?", CorrectOption: "A", OptionA: "Finite automaton", OptionB: "Pushdown automaton", OptionC: "Turing machine", OptionD: "Context-free automaton", AnswerExplanation: "Finite automata are used to recognize tokens denoted by regular expressions.", Category: "Lexical Analysis" },
  { ID: 14, Question: "Which parser type is known for handling left recursion well?", CorrectOption: "D", OptionA: "Operator precedence parser", OptionB: "LL parser", OptionC: "Recursive descent parser", OptionD: "LR parser", AnswerExplanation: "LR parsers efficiently manage left-recursive grammars.", Category: "Syntax Analysis" },
  { ID: 15, Question: "What is the main drawback of operator precedence parsing?", CorrectOption: "B", OptionA: "Cannot detect semantic errors", OptionB: "Limited to certain operator grammars", OptionC: "Too slow for practical use", OptionD: "Generates incorrect parse trees", AnswerExplanation: "Operator precedence parsers can only handle a subset of context-free grammars.", Category: "Syntax Analysis" },
  { ID: 16, Question: "Quads and triples are related to which compiler phase?", CorrectOption: "B", OptionA: "Symbol table management", OptionB: "Intermediate code representation", OptionC: "Code optimization", OptionD: "Error handling", AnswerExplanation: "Quads and triples are intermediate code representations used after semantic analysis.", Category: "Intermediate Code" },
  { ID: 17, Question: "What is the purpose of code optimization?", CorrectOption: "C", OptionA: "Detect syntax errors", OptionB: "Generate symbol tables", OptionC: "Improve efficiency of generated code", OptionD: "Parse source code", AnswerExplanation: "Code optimization improves speed, size, or power efficiency of compiled code.", Category: "Code Optimization" },
  { ID: 18, Question: "A loader is responsible for:", CorrectOption: "A", OptionA: "Loading executable files into memory", OptionB: "Translating code", OptionC: "Combining object files", OptionD: "Checking semantic errors", AnswerExplanation: "Loaders prepare executables in memory and initialize registers for execution.", Category: "System Programs" },
  { ID: 19, Question: "Which of the following is NOT a phase in compilation?", CorrectOption: "D", OptionA: "Lexical Analysis", OptionB: "Syntax Analysis", OptionC: "Semantic Analysis", OptionD: "Execution", AnswerExplanation: "Execution is performed by the computer after compilation, not a compilation phase.", Category: "Compilation Process" },
  { ID: 20, Question: "What does the symbol table store?", CorrectOption: "A", OptionA: "Information about identifiers", OptionB: "Optimized code", OptionC: "Source code tokens", OptionD: "Error messages", AnswerExplanation: "The symbol table contains data about variable names, types, scope, etc.", Category: "Compiler Data Structures" },
  { ID: 21, Question: "Which is a common method for error recovery in compilers?", CorrectOption: "C", OptionA: "Immediate program abort", OptionB: "Ignore all errors", OptionC: "Panic mode recovery", OptionD: "Generate incorrect code", AnswerExplanation: "Panic mode discards input until a safe point to resume parsing.", Category: "Error Handling" },
  { ID: 22, Question: "Which of these is a Chomsky Type-3 grammar?", CorrectOption: "B", OptionA: "Context-sensitive grammar", OptionB: "Regular grammar", OptionC: "Context-free grammar", OptionD: "Unrestricted grammar", AnswerExplanation: "Type-3 grammars describe regular languages.", Category: "Grammar Types" },
  { ID: 23, Question: "Which data structure is primarily used in syntax analysis?", CorrectOption: "D", OptionA: "Queue", OptionB: "Hash table", OptionC: "Linked list", OptionD: "Stack", AnswerExplanation: "Stacks are used for managing parser states and symbol matching.", Category: "Syntax Analysis" },
  { ID: 24, Question: "Semantic errors include all EXCEPT:", CorrectOption: "A", OptionA: "Typographical errors", OptionB: "Type incompatibility", OptionC: "Use of undeclared variables", OptionD: "Invalid function arguments", AnswerExplanation: "Typographical errors are lexical or syntactic, not semantic errors.", Category: "Semantic Analysis" },
  { ID: 25, Question: "Which is true about a symbol’s 'binding' in programming languages?", CorrectOption: "C", OptionA: "It changes at runtime only", OptionB: "Determines syntax rules", OptionC: "Associates attributes like type or storage", OptionD: "Is unrelated to semantics", AnswerExplanation: "Binding associates symbolic names with properties like type and memory location.", Category: "Programming Languages" },
  { ID: 26, Question: "What does 'bootstrapping' a compiler mean?", CorrectOption: "B", OptionA: "Debugging compiled code", OptionB: "Writing a compiler in the language it compiles", OptionC: "Optimizing compiler code", OptionD: "Loading executable files", AnswerExplanation: "Bootstrapping involves implementing the compiler using the language it compiles.", Category: "Compiler Construction" },
  { ID: 27, Question: "What is the 'Longest Match Rule' in lexical analysis?", CorrectOption: "C", OptionA: "Match the smallest valid token", OptionB: "Ignore whitespace tokens", OptionC: "Match the longest possible token in input", OptionD: "Match tokens randomly", AnswerExplanation: "The longest valid token is chosen when multiple matches are possible.", Category: "Lexical Analysis" },
  { ID: 28, Question: "What is the main purpose of 'type checking'?", CorrectOption: "A", OptionA: "Ensure operations are performed on compatible data types", OptionB: "Detect syntax errors", OptionC: "Optimize memory usage", OptionD: "Generate intermediate code", AnswerExplanation: "Type checking verifies that operands of operators have compatible types.", Category: "Semantic Analysis" },
  { ID: 29, Question: "In code generation, what is a key challenge?", CorrectOption: "B", OptionA: "Parsing input files", OptionB: "Mapping intermediate code to machine instructions", OptionC: "Lexical tokenizing", OptionD: "Syntax tree creation", AnswerExplanation: "Code generation translates intermediate representation into target machine instructions.", Category: "Code Generation" },
  { ID: 30, Question: "Which is NOT a quality of a good compiler?", CorrectOption: "D", OptionA: "Accuracy", OptionB: "Efficiency", OptionC: "Maintainability", OptionD: "Ability to run programs", AnswerExplanation: "Running programs is a function of the computer, not the compiler.", Category: "Compiler Qualities" },
  {
    ID: 31,
    Question: "According to Study Session 1, what is a fundamental characteristic of high-level languages?",
    CorrectOption: "B",
    OptionA: "They use numeric machine operation codes.",
    OptionB: "They are human-friendly and easy to write.",
    OptionC: "They are based on a particular microprocessor.",
    OptionD: "They consist of combinations of 0s and 1s.",
    AnswerExplanation: "High-level languages are described as English-like, flexible, easy to write, easy to understand, and human-friendly.",
    Category: "Programming Languages",
  },
  {
    ID: 32,
    Question: "Which type of computer language is characterized by mnemonics like STA, LDA, and ADD?",
    CorrectOption: "A",
    OptionA: "Assembly Language",
    OptionB: "High-level Language",
    OptionC: "Machine Language",
    OptionD: "Object-Oriented Language",
    AnswerExplanation: "Assembly language uses mnemonics and is nearer to machine language.",
    Category: "Programming Languages",
  },
  {
    ID: 33,
    Question: "What is the ONLY language directly understood by the computer?",
    CorrectOption: "C",
    OptionA: "High-level Language",
    OptionB: "Assembly Language",
    OptionC: "Machine Language",
    OptionD: "Source Language",
    AnswerExplanation: "The machine language, consisting of 0s and 1s, is the only language the computer understands.",
    Category: "Programming Languages",
  },
  {
    ID: 34,
    Question: "What is the primary reason for learning linguistic analysis in compiler design?",
    CorrectOption: "A",
    OptionA: "To understand the structure of programming languages.",
    OptionB: "To write more efficient machine code.",
    OptionC: "To implement new hardware architectures.",
    OptionD: "To debug runtime errors more effectively.",
    AnswerExplanation: "The rationale is to understand the structure of programming languages.",
    Category: "Linguistic Analysis",
  },
  {
    ID: 35,
    Question: "Which concept defines a language as 'a set of sentences over an alphabet with an associated rule of formation'?",
    CorrectOption: "A",
    OptionA: "Meaning of a Language",
    OptionB: "Translator definition",
    OptionC: "Semantic analysis",
    OptionD: "Lexical analysis",
    AnswerExplanation: "This is the definition of a language provided in Study Session 1.",
    Category: "Linguistic Analysis",
  },

  // Study Session 3: Types of Grammar
  {
    ID: 36,
    Question: "Which Chomsky type of grammar corresponds to regular languages and is the least powerful?",
    CorrectOption: "D",
    OptionA: "Type Zero",
    OptionB: "Type One",
    OptionC: "Type Two",
    OptionD: "Type Three",
    AnswerExplanation: "Chomsky Type Three grammars generate regular languages.",
    Category: "Grammar Types",
  },
  {
    ID: 37,
    Question: "Context-Free Grammars belong to which Chomsky type?",
    CorrectOption: "C",
    OptionA: "Type Zero",
    OptionB: "Type One",
    OptionC: "Type Two",
    OptionD: "Type Three",
    AnswerExplanation: "Context-Free Grammars are Chomsky Type Two.",
    Category: "Grammar Types",
  },
  {
    ID: 38,
    Question: "What is a characteristic of an 'ambiguous context-free grammar'?",
    CorrectOption: "B",
    OptionA: "It generates only regular languages.",
    OptionB: "It allows a string to have more than one leftmost derivation or parse tree.",
    OptionC: "It requires context to parse correctly.",
    OptionD: "It is only used in machine language.",
    AnswerExplanation: "An ambiguous grammar can produce multiple parse trees for the same string.",
    Category: "Grammar Types",
  },
  {
    ID: 39,
    Question: "Grammars like Operator Precedence Grammars are primarily concerned with:",
    CorrectOption: "A",
    OptionA: "Defining the hierarchy of operators in expressions.",
    OptionB: "Recognizing tokens in the input stream.",
    OptionC: "Optimizing the generated machine code.",
    OptionD: "Checking for type compatibility.",
    AnswerExplanation: "Operator precedence grammars are used to define how operators in expressions are evaluated.",
    Category: "Grammar Types",
  },
  {
    ID: 40,
    Question: "Which Chomsky Type is the most powerful and can generate any recursively enumerable language?",
    CorrectOption: "A",
    OptionA: "Type Zero",
    OptionB: "Type One",
    OptionC: "Type Two",
    OptionD: "Type Three",
    AnswerExplanation: "Type Zero (Unrestricted Grammars) are the most powerful.",
    Category: "Grammar Types",
  },

  // Study Session 4: Regular Expressions and Finite Automata
  {
    ID: 41,
    Question: "Regular expressions are primarily used in which phase of compilation?",
    CorrectOption: "A",
    OptionA: "Lexical Analysis",
    OptionB: "Syntax Analysis",
    OptionC: "Semantic Analysis",
    OptionD: "Code Generation",
    AnswerExplanation: "Regular expressions define the patterns for tokens recognized by the lexical analyzer.",
    Category: "Regular Expressions",
  },
  {
    ID: 42,
    Question: "What does the '*' operation in regular expressions signify?",
    CorrectOption: "D",
    OptionA: "One or more occurrences",
    OptionB: "Zero or one occurrence",
    OptionC: "Concatenation",
    OptionD: "Zero or more occurrences",
    AnswerExplanation: "Kleene star (*) means zero or more repetitions.",
    Category: "Regular Expressions",
  },
  {
    ID: 43,
    Question: "A Finite Automaton is a mathematical model for recognizing languages described by which of the following?",
    CorrectOption: "C",
    OptionA: "Context-free grammars",
    OptionB: "Turing machines",
    OptionC: "Regular expressions",
    OptionD: "Context-sensitive grammars",
    AnswerExplanation: "Finite automata recognize regular languages, which are described by regular expressions.",
    Category: "Finite Automata",
  },
  {
    ID: 44,
    Question: "What is the 'Longest Match Rule' in the context of lexical analysis?",
    CorrectOption: "A",
    OptionA: "When an input string matches multiple regular expressions, the one that matches the longest prefix is chosen.",
    OptionB: "Always choose the shortest possible token.",
    OptionC: "Tokens must be exactly the length of the regular expression.",
    OptionD: "Only regular expressions that perfectly match the entire input are accepted.",
    AnswerExplanation: "The Longest Match Rule ensures that the lexical analyzer forms the longest possible valid token.",
    Category: "Lexical Analysis",
  },
  {
    ID: 45,
    Question: "Which symbol in regular expressions typically denotes 'OR' or 'alternation'?",
    CorrectOption: "B",
    OptionA: "*",
    OptionB: "|",
    OptionC: "+",
    OptionD: "?",
    AnswerExplanation: "The pipe symbol (|) indicates a choice between alternatives.",
    Category: "Regular Expressions",
  },
  {
    ID: 46,
    Question: "What is the primary function of a Non-deterministic Finite Automaton (NFA)?",
    CorrectOption: "D",
    OptionA: "To generate machine code directly.",
    OptionB: "To perform semantic checks on code.",
    OptionC: "To provide a unique path for every input string.",
    OptionD: "To recognize tokens with multiple possible next states for a given input.",
    AnswerExplanation: "NFAs can have multiple transitions for the same input symbol, leading to multiple possible states.",
    Category: "Finite Automata",
  },
  {
    ID: 47,
    Question: "What is the main difference between a Deterministic Finite Automaton (DFA) and a Non-deterministic Finite Automaton (NFA)?",
    CorrectOption: "A",
    OptionA: "DFAs have a unique transition for each state-input pair, NFAs do not.",
    OptionB: "NFAs are more powerful than DFAs.",
    OptionC: "DFAs cannot recognize regular languages, NFAs can.",
    OptionD: "NFAs are always simpler to construct than DFAs.",
    AnswerExplanation: "DFAs have a single, determined next state for every input and state.",
    Category: "Finite Automata",
  },

  // Study Session 5: Overview of a Compiler
  {
    ID: 48,
    Question: "Which of these is considered a 'structural component' of a compiler?",
    CorrectOption: "A",
    OptionA: "Lexical Analyzer",
    OptionB: "Operating System",
    OptionC: "Hardware Processor",
    OptionD: "User Interface",
    AnswerExplanation: "The lexical analyzer is the first phase, a core component of a compiler.",
    Category: "Compiler Architecture",
  },
  {
    ID: 49,
    Question: "The Symbol Table in a compiler stores:",
    CorrectOption: "D",
    OptionA: "The machine code instructions.",
    OptionB: "The optimized source code.",
    OptionC: "Only error messages.",
    OptionD: "Information about identifiers, types, and scopes.",
    AnswerExplanation: "The symbol table is a data structure storing information about program entities.",
    Category: "Compiler Data Structures",
  },
  {
    ID: 50,
    Question: "What prepares the code for code generation by converting syntax trees into an intermediate representation?",
    CorrectOption: "B",
    OptionA: "The Scanner",
    OptionB: "Preparation for Code Generation",
    OptionC: "The Linker",
    OptionD: "The Loader",
    AnswerExplanation: "This phase generates an intermediate code from the parse tree before actual machine code generation.",
    Category: "Compilation Process",
  },
  {
    ID: 51,
    Question: "Which type of compiler translates source code into machine code for execution on the same machine?",
    CorrectOption: "A",
    OptionA: "Native Compiler",
    OptionB: "Cross-Compiler",
    OptionC: "Interpreter",
    OptionD: "Assembler",
    AnswerExplanation: "A native compiler produces code for the machine it runs on.",
    Category: "Types of Compilers",
  },
  {
    ID: 52,
    Question: "What is a 'quality of a good compiler' mentioned in the course material?",
    CorrectOption: "C",
    OptionA: "It must be open source.",
    OptionB: "It should always be an interpreter.",
    OptionC: "It should produce efficient target code.",
    OptionD: "It should be able to write its own code.",
    AnswerExplanation: "Efficiency of target code, speed of compilation, and good error handling are qualities.",
    Category: "Compiler Qualities",
  },
  {
    ID: 53,
    Question: "Which component of a compiler is also known as the 'Lexical Analyzer'?",
    CorrectOption: "B",
    OptionA: "The Parser",
    OptionB: "The Scanner",
    OptionC: "The Code Generator",
    OptionD: "The Optimizer",
    AnswerExplanation: "The terms scanner and lexical analyzer are used interchangeably.",
    Category: "Compiler Architecture",
  },

  // Study Session 6: Structure of Programming Languages
  {
    ID: 54,
    Question: "The 'syntax' of a programming language refers to:",
    CorrectOption: "C",
    OptionA: "The meaning of programs.",
    OptionB: "How programs are executed.",
    OptionC: "The set of rules that defines how programs are structured.",
    OptionD: "The memory management system.",
    AnswerExplanation: "Syntax defines the grammatical rules for forming valid programs.",
    Category: "Language Structure",
  },
  {
    ID: 55,
    Question: "What is 'semantics' in the context of programming languages?",
    CorrectOption: "A",
    OptionA: "The meaning of programs and statements.",
    OptionB: "The rules for variable naming.",
    OptionC: "The order of operations.",
    OptionD: "The process of compilation.",
    AnswerExplanation: "Semantics deals with the meaning and interpretation of constructs.",
    Category: "Language Structure",
  },
  {
    ID: 56,
    Question: "Which concept defines the association of attributes (like type, storage) with a program entity?",
    CorrectOption: "A",
    OptionA: "Binding",
    OptionB: "Coercion",
    OptionC: "Tokenization",
    OptionD: "Derivation",
    AnswerExplanation: "Binding connects a name to a property.",
    Category: "Language Structure",
  },
  {
    ID: 57,
    Question: "What are 'Tokens' in a programming language?",
    CorrectOption: "D",
    OptionA: "The smallest units of executable code.",
    OptionB: "Only keywords like 'if', 'else'.",
    OptionC: "The result of code generation.",
    OptionD: "The smallest meaningful units of a program recognized by the lexical analyzer.",
    AnswerExplanation: "Tokens are elementary building blocks like keywords, identifiers, operators, etc.",
    Category: "Language Structure",
  },
  {
    ID: 58,
    Question: "What is 'Coercion of Data Types'?",
    CorrectOption: "B",
    OptionA: "Explicit type casting by the programmer.",
    OptionB: "Automatic conversion of data types by the compiler.",
    OptionC: "A semantic error related to type mismatch.",
    OptionD: "The process of defining new data types.",
    AnswerExplanation: "Coercion refers to implicit type conversions.",
    Category: "Language Structure",
  },
  {
    ID: 59,
    Question: "What is involved in 'Parameter Transmission' in programming languages?",
    CorrectOption: "A",
    OptionA: "How arguments are passed to and from functions.",
    OptionB: "The way data is transmitted over a network.",
    OptionC: "Storing variables in different memory locations.",
    OptionD: "The process of optimizing function calls.",
    AnswerExplanation: "Parameter transmission refers to mechanisms like call-by-value, call-by-reference.",
    Category: "Language Structure",
  },

  // Study Session 7: Lexical Analysis (Scanners)
  {
    ID: 60,
    Question: "What is the primary task of a Lexical Analyzer (Scanner)?",
    CorrectOption: "C",
    OptionA: "Building a parse tree.",
    OptionB: "Detecting semantic errors.",
    OptionC: "Converting a stream of characters into a stream of tokens.",
    OptionD: "Generating machine code.",
    AnswerExplanation: "The scanner reads characters and groups them into tokens.",
    Category: "Lexical Analysis",
  },
  {
    ID: 61,
    Question: "Which of the following is NOT typically a task of the lexical analyzer?",
    CorrectOption: "D",
    OptionA: "Removing comments and whitespace.",
    OptionB: "Identifying keywords and identifiers.",
    OptionC: "Reporting lexical errors.",
    OptionD: "Checking for type compatibility.",
    AnswerExplanation: "Type compatibility is a semantic analysis task.",
    Category: "Lexical Analysis",
  },
  {
    ID: 62,
    Question: "How is a scanner typically implemented?",
    CorrectOption: "A",
    OptionA: "Using finite automata derived from regular expressions.",
    OptionB: "Using pushdown automata.",
    OptionC: "Using Turing machines.",
    OptionD: "Using recursive descent parsing.",
    AnswerExplanation: "Scanners are often built using finite automata, which recognize regular languages (defined by regular expressions).",
    Category: "Lexical Analysis",
  },
  {
    ID: 63,
    Question: "What is a 'lexeme' in lexical analysis?",
    CorrectOption: "B",
    OptionA: "A type of error.",
    OptionB: "A sequence of characters in the source program that matches a pattern for a token.",
    OptionC: "The output of the parser.",
    OptionD: "An entry in the symbol table.",
    AnswerExplanation: "A lexeme is the actual sequence of characters that forms a token.",
    Category: "Lexical Analysis",
  },

  // Study Session 8: Syntax Analysis (Parsers)
  {
    ID: 64,
    Question: "The primary output of the Syntax Analyzer (Parser) is typically a:",
    CorrectOption: "A",
    OptionA: "Parse tree or syntax tree.",
    OptionB: "Stream of tokens.",
    OptionC: "Optimized machine code.",
    OptionD: "Symbol table.",
    AnswerExplanation: "The parser builds a tree representation of the program's grammatical structure.",
    Category: "Syntax Analysis",
  },
  {
    ID: 65,
    Question: "What is 'Derivation' in the context of formal languages?",
    CorrectOption: "B",
    OptionA: "The process of compiling a program.",
    OptionB: "The process of applying grammar rules to transform start symbol into a string.",
    OptionC: "The conversion of tokens to lexemes.",
    OptionD: "The optimization of code.",
    AnswerExplanation: "Derivation applies production rules to generate strings from the grammar's start symbol.",
    Category: "Syntax Analysis",
  },
  {
    ID: 66,
    Question: "What does 'Left Recursion' refer to in grammar rules?",
    CorrectOption: "D",
    OptionA: "A rule where a non-terminal is followed by itself.",
    OptionB: "A rule that generates tokens in reverse order.",
    OptionC: "A grammar that produces a parse tree from right to left.",
    OptionD: "A grammar production where the leftmost symbol on the right-hand side is the same as the non-terminal on the left-hand side.",
    AnswerExplanation: "Left recursion (e.g., A -> A alpha) causes infinite loops in top-down parsers.",
    Category: "Syntax Analysis",
  },
  {
    ID: 67,
    Question: "What is 'Left Factoring' used for in grammar transformation?",
    CorrectOption: "C",
    OptionA: "To introduce left recursion.",
    OptionB: "To remove ambiguity from a grammar.",
    OptionC: "To remove common prefixes from alternative productions to enable top-down parsing.",
    OptionD: "To combine multiple grammars into one.",
    AnswerExplanation: "Left factoring extracts common prefixes to resolve issues for predictive parsers.",
    Category: "Syntax Analysis",
  },
  {
    ID: 68,
    Question: "Which set is used in predictive parsing to determine which production to use based on the current input symbol?",
    CorrectOption: "A",
    OptionA: "FIRST and FOLLOW sets",
    OptionB: "LEFT and RIGHT sets",
    OptionC: "NEXT and PREVIOUS sets",
    OptionD: "BEGIN and END sets",
    AnswerExplanation: "FIRST and FOLLOW sets are crucial for constructing LL(1) parsers.",
    Category: "Syntax Analysis",
  },
  {
    ID: 69,
    Question: "What is a disadvantage of Operator Precedence Parsers?",
    CorrectOption: "B",
    OptionA: "They are very slow.",
    OptionB: "They cannot handle all context-free grammars, only operator grammars.",
    OptionC: "They always produce ambiguous parse trees.",
    OptionD: "They require extensive manual coding.",
    AnswerExplanation: "Their applicability is limited to a specific class of grammars.",
    Category: "Syntax Analysis",
  },
  {
    ID: 70,
    Question: "What is 'Associativity' in the context of operators?",
    CorrectOption: "C",
    OptionA: "The priority of an operator over others.",
    OptionB: "How an operator relates to data types.",
    OptionC: "The grouping of operators with the same precedence (e.g., left-to-right for addition).",
    OptionD: "The ability of an operator to work with multiple operands.",
    AnswerExplanation: "Associativity defines how operators of the same precedence are grouped (e.g., `a - b - c` is `(a - b) - c` for left-associative).",
    Category: "Syntax Analysis",
  },
  {
    ID: 71,
    Question: "Which parsing type builds the parse tree from the start symbol down to the input string?",
    CorrectOption: "A",
    OptionA: "Top-down parsing",
    OptionB: "Bottom-up parsing",
    OptionC: "Left-to-right parsing",
    OptionD: "Right-to-left parsing",
    AnswerExplanation: "Top-down parsing starts from the root of the parse tree.",
    Category: "Syntax Analysis",
  },
  {
    ID: 72,
    Question: "An LL(1) parser is a type of:",
    CorrectOption: "A",
    OptionA: "Top-down parser",
    OptionB: "Bottom-up parser",
    OptionC: "Operator precedence parser",
    OptionD: "LR parser",
    AnswerExplanation: "LL(k) parsers are predictive top-down parsers.",
    Category: "Syntax Analysis",
  },
  {
    ID: 73,
    Question: "Which of these is a limitation of Syntax Analyzers?",
    CorrectOption: "B",
    OptionA: "They cannot detect lexical errors.",
    OptionB: "They cannot detect all semantic errors (e.g., undeclared variables).",
    OptionC: "They are too slow for large programs.",
    OptionD: "They can only work with regular grammars.",
    AnswerExplanation: "Semantic errors like type checking or variable declarations are handled in the semantic analysis phase.",
    Category: "Syntax Analysis",
  },

  // Study Session 9: Semantic Analysis
  {
    ID: 74,
    Question: "What is the primary function of Semantic Analysis in a compiler?",
    CorrectOption: "C",
    OptionA: "To convert characters into tokens.",
    OptionB: "To build the parse tree.",
    OptionC: "To check for meaning and consistency of the program, e.g., type checking.",
    OptionD: "To optimize the machine code.",
    AnswerExplanation: "Semantic analysis ensures the program is logically sound and adheres to language rules beyond syntax.",
    Category: "Semantic Analysis",
  },
  {
    ID: 75,
    Question: "Why is Semantic Analysis often a separate phase from Syntax Analysis?",
    CorrectOption: "A",
    OptionA: "Syntax analysis focuses only on structure, while semantic analysis deals with meaning and context-sensitive checks.",
    OptionB: "Semantic analysis is always performed before lexical analysis.",
    OptionC: "Syntax analysis is faster if done separately.",
    OptionD: "Semantic analysis cannot be automated.",
    AnswerExplanation: "Separation allows specialized checks that go beyond context-free grammar rules.",
    Category: "Semantic Analysis",
  },
  {
    ID: 76,
    Question: "Which type of semantic error involves an operation applied to data of an incompatible type?",
    CorrectOption: "D",
    OptionA: "Undeclared variable",
    OptionB: "Missing semicolon",
    OptionC: "Infinite loop",
    OptionD: "Type mismatch",
    AnswerExplanation: "Type mismatch (e.g., adding an integer to a string) is a common semantic error.",
    Category: "Semantic Analysis",
  },
  {
    ID: 77,
    Question: "What is 'Polish Notation' (or Prefix Notation) used for in compilers?",
    CorrectOption: "B",
    OptionA: "Representing source code.",
    OptionB: "Representing arithmetic expressions without ambiguity (e.g., using a stack-based evaluation).",
    OptionC: "Defining lexical tokens.",
    OptionD: "Optimizing memory allocation.",
    AnswerExplanation: "Polish Notation (and Reverse Polish Notation) simplifies expression evaluation.",
    Category: "Intermediate Code",
  },
  {
    ID: 78,
    Question: "What is a 'Quadruple' as an intermediate code representation?",
    CorrectOption: "C",
    OptionA: "A single operation with one operand.",
    OptionB: "A set of four instructions in machine code.",
    OptionC: "A four-field record (operator, operand1, operand2, result).",
    OptionD: "A tree structure with four nodes.",
    AnswerExplanation: "Quadruples are a common three-address code format for intermediate representation.",
    Category: "Intermediate Code",
  },
  {
    ID: 79,
    Question: "What is a 'Triple' as an intermediate code representation?",
    CorrectOption: "A",
    OptionA: "A three-field record (operator, operand1, operand2) where results are referenced by their position.",
    OptionB: "A set of three machine instructions.",
    OptionC: "A four-field record similar to a quadruple.",
    OptionD: "A simplified assembly instruction.",
    AnswerExplanation: "Triples implicitly refer to temporary results by their statement number, unlike quadruples.",
    Category: "Intermediate Code",
  },
  {
    ID: 80,
    Question: "Which of the following is NOT typically a functional module (semantic routine) for implementing a semantic analyzer?",
    CorrectOption: "D",
    OptionA: "Type checking routines",
    OptionB: "Symbol table management routines",
    OptionC: "Attribute evaluation routines",
    OptionD: "Lexical analysis routines",
    AnswerExplanation: "Lexical analysis routines belong to the scanner phase, not semantic analysis.",
    Category: "Semantic Analysis",
  },
  {
    ID: 81,
    Question: "What are 'Attribute Grammars' used for in compiler design?",
    CorrectOption: "B",
    OptionA: "To define the syntax of a language.",
    OptionB: "To formally specify the semantics of a language by associating attributes with grammar symbols.",
    OptionC: "To generate regular expressions.",
    OptionD: "To perform code optimization.",
    AnswerExplanation: "Attribute grammars add semantic rules to context-free grammars to define meaning.",
    Category: "Semantic Analysis",
  },

  // Study Session 10: Code Optimization and Generation
  {
    ID: 82,
    Question: "The primary goal of 'Code Optimization' is to:",
    CorrectOption: "A",
    OptionA: "Improve the performance (speed, size) of the generated machine code.",
    OptionB: "Catch syntax errors.",
    OptionC: "Translate high-level language to assembly language.",
    OptionD: "Manage the symbol table.",
    AnswerExplanation: "Optimization aims to make the target code more efficient.",
    Category: "Code Optimization",
  },
  {
    ID: 83,
    Question: "Which of these is an example of an 'instance of optimization' in code?",
    CorrectOption: "C",
    OptionA: "Converting source code to tokens.",
    OptionB: "Building a parse tree.",
    OptionC: "Removing unreachable code or dead code elimination.",
    OptionD: "Type checking for expressions.",
    AnswerExplanation: "Dead code elimination is a classic optimization technique.",
    Category: "Code Optimization",
  },
  {
    ID: 84,
    Question: "What is 'Compiler Bootstrapping'?",
    CorrectOption: "B",
    OptionA: "The initial loading of the operating system.",
    OptionB: "Developing a compiler for language X using language X itself.",
    OptionC: "The process of linking libraries to an executable.",
    OptionD: "The final phase of compilation, generating executable code.",
    AnswerExplanation: "Bootstrapping is a technique to self-compile a compiler.",
    Category: "Compiler Construction",
  },
  {
    ID: 85,
    Question: "Which phase of the compiler generates the final machine code or assembly code?",
    CorrectOption: "D",
    OptionA: "Lexical Analysis",
    OptionB: "Semantic Analysis",
    OptionC: "Code Optimization",
    OptionD: "Code Generation",
    AnswerExplanation: "Code generation is the final stage that produces the target code.",
    Category: "Code Generation",
  },
  {
    ID: 86,
    Question: "What is 'Loop Optimization'?",
    CorrectOption: "A",
    OptionA: "Techniques to improve the execution speed of loops by reducing overhead or redundant computations.",
    OptionB: "A type of syntax error.",
    OptionC: "The process of creating infinite loops.",
    OptionD: "A method for parsing recursive grammars.",
    AnswerExplanation: "Loops are critical for performance, so specific optimizations target them (e.g., loop invariant code motion).",
    Category: "Code Optimization",
  },
  {
    ID: 87,
    Question: "What is the primary input to the 'Code Generation' phase?",
    CorrectOption: "B",
    OptionA: "Raw source code.",
    OptionB: "Intermediate code representation (e.g., quadruples, triples).",
    OptionC: "Lexical tokens.",
    OptionD: "Syntax tree.",
    AnswerExplanation: "Code generation typically works on the optimized intermediate representation.",
    Category: "Code Generation",
  },

  // Study Session 11: Error Handling in Compiler Design
  {
    ID: 88,
    Question: "What is the main purpose of 'Error Handling' in compilers?",
    CorrectOption: "C",
    OptionA: "To generate the fastest possible code.",
    OptionB: "To ensure that all programs compile successfully.",
    OptionC: "To detect and report errors, and if possible, recover to continue processing.",
    OptionD: "To create the symbol table.",
    AnswerExplanation: "Error handling aims to assist the programmer in finding and fixing errors.",
    Category: "Error Handling",
  },
  {
    ID: 89,
    Question: "Which error is typically classified as a 'lexical error'?",
    CorrectOption: "A",
    OptionA: "Misspelled keyword (e.g., 'whiile' instead of 'while').",
    OptionB: "Missing semicolon at the end of a statement.",
    OptionC: "Type mismatch between an integer and a string.",
    OptionD: "Division by zero.",
    AnswerExplanation: "Lexical errors are typically misspellings or illegal characters that prevent token formation.",
    Category: "Error Handling",
  },
  {
    ID: 90,
    Question: "A 'syntax error' is characterized by:",
    CorrectOption: "B",
    OptionA: "Incorrect data types.",
    OptionB: "Violation of the grammatical rules of the language.",
    OptionC: "Logical errors in the program.",
    OptionD: "Run-time errors.",
    AnswerExplanation: "Syntax errors are structural mistakes, like a missing parenthesis or misplaced keyword.",
    Category: "Error Handling",
  },
  {
    ID: 91,
    Question: "An 'undeclared variable' error is an example of what type of error?",
    CorrectOption: "C",
    OptionA: "Lexical error",
    OptionB: "Syntax error",
    OptionC: "Semantic error",
    OptionD: "Run-time error",
    AnswerExplanation: "Semantic analysis checks for declarations and scope issues.",
    Category: "Error Handling",
  },
  {
    ID: 92,
    Question: "What is a 'Run-time error'?",
    CorrectOption: "D",
    OptionA: "An error detected during lexical analysis.",
    OptionB: "An error in the compiler itself.",
    OptionC: "An error detected during semantic analysis.",
    OptionD: "An error that occurs during the execution of a compiled program.",
    AnswerExplanation: "Run-time errors include issues like division by zero or out-of-bounds array access.",
    Category: "Error Handling",
  },
  {
    ID: 93,
    Question: "Which of these is a desirable quality (wish list) of an 'Error Handler'?",
    CorrectOption: "A",
    OptionA: "It should accurately report the location and nature of the error.",
    OptionB: "It should compile all programs, even with errors.",
    OptionC: "It should automatically fix all errors without user intervention.",
    OptionD: "It should only report one error at a time.",
    AnswerExplanation: "Accuracy in reporting is crucial for effective debugging.",
    Category: "Error Handling",
  },
  {
    ID: 94,
    Question: "What is 'Panic Mode' error recovery?",
    CorrectOption: "B",
    OptionA: "Revising the entire program.",
    OptionB: "Discarding input symbols one by one until a synchronizing token is found.",
    OptionC: "Automatically correcting all errors.",
    OptionD: "Generating a new grammar to handle the error.",
    AnswerExplanation: "Panic mode is a simple error recovery strategy that skips input until a 'safe' point.",
    Category: "Error Handling",
  },
  {
    ID: 95,
    Question: "Which phase of compilation is primarily responsible for detecting and reporting errors related to missing semicolons or mismatched parentheses?",
    CorrectOption: "B",
    OptionA: "Lexical Analysis",
    OptionB: "Syntax Analysis",
    OptionC: "Semantic Analysis",
    OptionD: "Code Generation",
    AnswerExplanation: "These are structural errors detected by the parser.",
    Category: "Error Handling",
  },
  {
    ID: 96,
    Question: "If a compiler reports an error like 'undeclared identifier', which phase most likely detected this error?",
    CorrectOption: "C",
    OptionA: "Lexical Analysis",
    OptionB: "Syntax Analysis",
    OptionC: "Semantic Analysis",
    OptionD: "Code Generation",
    AnswerExplanation: "Checking if identifiers are declared and used correctly falls under semantic analysis, often via the symbol table.",
    Category: "Error Handling",
  },
  {
    ID: 97,
    Question: "What happens if an interpreter encounters an error during execution?",
    CorrectOption: "A",
    OptionA: "It stops execution and reports the error immediately.",
    OptionB: "It compiles the rest of the program before reporting.",
    OptionC: "It tries to fix the error automatically.",
    OptionD: "It always produces an object file before stopping.",
    AnswerExplanation: "Interpreters are known for stopping at the first error.",
    Category: "Compilers vs Interpreters",
  },
  {
    ID: 98,
    Question: "Which phase of compiler acts as an interface to the rest of the compilation process by producing an intermediate representation?",
    CorrectOption: "C",
    OptionA: "Lexical analysis",
    OptionB: "Code generation",
    OptionC: "Semantic analysis",
    OptionD: "Code optimization",
    AnswerExplanation: "Semantic analysis often produces the annotated syntax tree or intermediate code that subsequent phases consume.",
    Category: "Compilation Process",
  },
  {
    ID: 99,
    Question: "What is the primary role of the symbol table in error reporting?",
    CorrectOption: "A",
    OptionA: "To provide contextual information about identifiers for error messages.",
    OptionB: "To store the errors themselves.",
    OptionC: "To convert errors into warnings.",
    OptionD: "To execute error recovery routines.",
    AnswerExplanation: "The symbol table holds attribute information that helps in generating informative error messages.",
    Category: "Error Handling",
  },
  {
    ID: 100,
    Question: "Which phase of the compiler architecture deals with the 'architecture of a compiler' and 'code-directed compilation'?",
    CorrectOption: "D",
    OptionA: "Lexical Analyzer",
    OptionB: "Semantic Analyzer",
    OptionC: "Code Optimization",
    OptionD: "General Introduction and Overview", // This relates to the course curriculum contents directly.
    AnswerExplanation: "The overall architecture and code-directed compilation are topics covered at a high level in the introductory sections before delving into specific phases.",
    Category: "Compiler Architecture",
  },
]