export const apiData = {"response_code":0,"results":[{"type":"multiple","difficulty":"easy","category":"Entertainment: Cartoon &amp; Animations","question":"What is the relationship between Rick and Morty in the show &quot;Rick and Morty&quot;?","correct_answer":"Grandfather and Grandson","incorrect_answers":["Father and Son","Best Friends","Crimefighting Partners"]},{"type":"multiple","difficulty":"easy","category":"Entertainment: Cartoon &amp; Animations","question":"Wendy O. Koopa appeared in the Super Mario DIC Cartoons, but what was she known as?","correct_answer":"Kootie Pie","incorrect_answers":["Sweetie Pie","Wendy Pie","Honey Pie"]},{"type":"multiple","difficulty":"hard","category":"Entertainment: Cartoon &amp; Animations","question":"Which of the following films was Don Bluth both the writer, director, and producer for?","correct_answer":"All Dogs Go To Heaven","incorrect_answers":["Titan A.E.","Anastasia","The Land Before Time"]},{"type":"multiple","difficulty":"easy","category":"Entertainment: Cartoon &amp; Animations","question":"Who created the Cartoon Network series &quot;Adventure Time&quot;?","correct_answer":"Pendleton Ward","incorrect_answers":["J. G. Quintel","Ben Bocquelet","Rebecca Sugar"]},{"type":"multiple","difficulty":"medium","category":"Entertainment: Cartoon &amp; Animations","question":"What was the number on Gerald&#039;s shirt in &quot;Hey Arnold!&quot;?","correct_answer":"33","incorrect_answers":["88","38","83"]},{"type":"multiple","difficulty":"easy","category":"Entertainment: Cartoon &amp; Animations","question":"What is Everest&#039;s favorite food in the Nickelodeon\/Nick Jr. series &quot;PAW Patrol&quot;?","correct_answer":"Liver","incorrect_answers":["Chicken","Steak","Caribou"]},{"type":"multiple","difficulty":"easy","category":"Entertainment: Cartoon &amp; Animations","question":"In the show &quot;Steven Universe&quot;, who are the main two employees of The Big Donut?","correct_answer":"Sadie and Lars","incorrect_answers":["Steven and James","Erik and Julie","Bob and May"]},{"type":"multiple","difficulty":"medium","category":"Entertainment: Cartoon &amp; Animations","question":"In &quot;The Amazing World of Gumball&quot;, who is the principal of Elmore Junior High?","correct_answer":"Principal Brown","incorrect_answers":["Principal Small","Principal Brawn","Principal Simeon"]},{"type":"multiple","difficulty":"easy","category":"Entertainment: Cartoon &amp; Animations","question":"Which of the following is not a Flintstones character?","correct_answer":"Lord Rockingham IX","incorrect_answers":["Rockhead Slate","The Great Gazoo","Barney Rubble"]},{"type":"multiple","difficulty":"medium","category":"Entertainment: Cartoon &amp; Animations","question":"What Cartoon Network show aired its first episode on November 4th, 2013?","correct_answer":"Steven Universe","incorrect_answers":["Regular Show","Adventure Time","The Amazing World of Gumball"]},{"type":"multiple","difficulty":"easy","category":"Entertainment: Cartoon &amp; Animations","question":"In the show &quot;Foster&#039;s Home For Imaginary Friends&quot;, which character had an obsession with basketball?","correct_answer":"Wilt","incorrect_answers":["Coco","Mac","Cheese"]},{"type":"multiple","difficulty":"medium","category":"Entertainment: Cartoon &amp; Animations","question":"Which episode from The Amazing World Of Gumball won the Childrens Choice Award at the British Animation Awards in 2016?","correct_answer":"The Shell","incorrect_answers":["The Limit","The Kids","The Gripes"]},{"type":"multiple","difficulty":"easy","category":"Entertainment: Cartoon &amp; Animations","question":"What is the name of the creatures that the protagonists of the webshow RWBY fight against?","correct_answer":"Grimm","incorrect_answers":["Reavers","Heartless","Dark Ones"]},{"type":"multiple","difficulty":"hard","category":"Entertainment: Cartoon &amp; Animations","question":"What was Maggie Simpson&#039;s first canonical word, not including the Tracey Ullman shorts?","correct_answer":"Daddy.","incorrect_answers":["Sequel?","Ja!","Rusty!"]},{"type":"multiple","difficulty":"hard","category":"Entertainment: Cartoon &amp; Animations","question":"In the 1969 Cartoon show &quot;Dastardly and Muttley in Their Flying Machines&quot;, which were NOT one of the lyrics in the opening theme?","correct_answer":"Stab him","incorrect_answers":["Nab him","Jab him","Tab him"]},{"type":"multiple","difficulty":"medium","category":"Entertainment: Cartoon &amp; Animations","question":"What is the name of the Alligator that The Simpsons &quot;killed&quot; in the episode &quot;Kill The Alligator and Run&quot;?","correct_answer":"Captain Jack","incorrect_answers":["Captain Jake","Captain Hector","Captain Flynn"]},{"type":"multiple","difficulty":"easy","category":"Entertainment: Cartoon &amp; Animations","question":"In the 1993 Disney animated series &quot;Bonkers&quot;, what is the name of Bonker&#039;s second partner?","correct_answer":"Miranda Wright","incorrect_answers":["Dick Tracy","Eddie Valiant","Dr. Ludwig von Drake"]},{"type":"multiple","difficulty":"easy","category":"Entertainment: Cartoon &amp; Animations","question":"What was the first Disney movie to use CGI?","correct_answer":"The Black Cauldron","incorrect_answers":["Tron","Toy Story","Fantasia"]},{"type":"multiple","difficulty":"medium","category":"Entertainment: Cartoon &amp; Animations","question":"In the Dreamworks animated movie &quot;Madagascar,&quot; who voices Maurice the lemur?","correct_answer":"Cedric the Entertainer","incorrect_answers":["Jack Black","Sacha Baron Cohen","Chris Rock"]},{"type":"multiple","difficulty":"hard","category":"Entertainment: Cartoon &amp; Animations","question":"Townsend Coleman provided the voice for which turtle in the original 1987 series of &quot;Teenage Mutant Ninja Turtles&quot;?","correct_answer":"Michelangelo","incorrect_answers":["Leonardo","Donatello","Raphael"]}]}

export const questions =[
  {
    "ID": 1,
    "Question": "Limnology is the study of which type of water bodies?",
    "CorrectOption": "Inland waters (fresh or saline, standing or running)",
    "OptionA": "Inland waters (fresh or saline, standing or running)",
    "OptionB": "Only oceans",
    "OptionC": "Glaciers exclusively",
    "OptionD": "Atmospheric vapor",
    "AnswerExplanation": "Limnology focuses on lakes, ponds, rivers, streams, wetlands, and other continental waters—not marine or atmospheric systems.",
    "Category": "Introduction"
  },
  {
    "ID": 2,
    "Question": "Which scientist is widely credited with the early development of limnology as a discipline?",
    "CorrectOption": "François-Alphonse Forel",
    "OptionA": "François-Alphonse Forel",
    "OptionB": "Charles Darwin",
    "OptionC": "Rachel Carson",
    "OptionD": "Jacques Cousteau",
    "AnswerExplanation": "Forel’s late-1800s work on Lake Geneva earned him the title “Father of Limnology.”",
    "Category": "History"
  },
  {
    "ID": 3,
    "Question": "The epilimnion of a lake is typically characterized by:",
    "CorrectOption": "Warm, well-oxygenated surface water",
    "OptionA": "Warm, well-oxygenated surface water",
    "OptionB": "Cold, low-oxygen deep water",
    "OptionC": "A rapid temperature decline",
    "OptionD": "Complete absence of light",
    "AnswerExplanation": "Sunlight warms the surface layer and wind mixing keeps it oxygen-rich.",
    "Category": "Physical Properties"
  },
  {
    "ID": 4,
    "Question": "Which term describes a lake that mixes from top to bottom once each year?",
    "CorrectOption": "Monomictic",
    "OptionA": "Monomictic",
    "OptionB": "Dimictic",
    "OptionC": "Polymictic",
    "OptionD": "Meromictic",
    "AnswerExplanation": "Monomictic lakes destratify and fully mix a single time annually, usually in winter (warm-monomictic) or summer (cold-monomictic).",
    "Category": "Physical Properties"
  },
  {
    "ID": 5,
    "Question": "In a typical dissolved-oxygen profile of an eutrophic lake during summer, the lowest oxygen is likely found:",
    "CorrectOption": "Near the sediment in the hypolimnion",
    "OptionA": "Near the sediment in the hypolimnion",
    "OptionB": "At the surface epilimnion",
    "OptionC": "Throughout the thermocline",
    "OptionD": "Uniformly at every depth",
    "AnswerExplanation": "Respiration and decomposition use up oxygen in the isolated, deep hypolimnion of eutrophic lakes.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 6,
    "Question": "Which nutrient most commonly limits algal growth in freshwater lakes?",
    "CorrectOption": "Phosphorus",
    "OptionA": "Phosphorus",
    "OptionB": "Sodium",
    "OptionC": "Calcium",
    "OptionD": "Silicon",
    "AnswerExplanation": "In many freshwaters, small phosphorus additions trigger large algal blooms, showing it is the limiting nutrient.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 7,
    "Question": "A secchi disk reading primarily estimates a lake's:",
    "CorrectOption": "Water transparency",
    "OptionA": "Water transparency",
    "OptionB": "Surface water temperature",
    "OptionC": "pH level",
    "OptionD": "Salinity",
    "AnswerExplanation": "The depth at which the disk disappears quantifies clarity and thus turbidity or color.",
    "Category": "Field Methods"
  },
  {
    "ID": 8,
    "Question": "Which watershed feature tends to increase surface runoff and reduce infiltration?",
    "CorrectOption": "High percentage of impervious surfaces",
    "OptionA": "High percentage of impervious surfaces",
    "OptionB": "Dense forest cover",
    "OptionC": "Gentle slopes with grassland",
    "OptionD": "Deep sandy soils",
    "AnswerExplanation": "Pavement and roofs prevent water from soaking in, causing faster, higher runoff peaks.",
    "Category": "Watershed"
  },
  {
    "ID": 9,
    "Question": "The term 'hyporheic zone' refers to:",
    "CorrectOption": "Subsurface region beneath and alongside a stream where groundwater and surface water mix",
    "OptionA": "Subsurface region beneath and alongside a stream where groundwater and surface water mix",
    "OptionB": "Open-water photic zone",
    "OptionC": "Deep lake sediments",
    "OptionD": "Evaporation layer at the air-water interface",
    "AnswerExplanation": "Water exchanges through porous sediments, affecting nutrients and temperature in streams.",
    "Category": "Hydrology"
  },
  {
    "ID": 10,
    "Question": "Which gas, produced under anoxic conditions in sediments, can contribute to greenhouse warming when released?",
    "CorrectOption": "Methane (CH₄)",
    "OptionA": "Methane (CH₄)",
    "OptionB": "Oxygen (O₂)",
    "OptionC": "Argon (Ar)",
    "OptionD": "Helium (He)",
    "AnswerExplanation": "Anaerobic decomposition yields methane, a potent greenhouse gas if it reaches the atmosphere.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 11,
    "Question": "Turbidity in lakes is commonly measured in:",
    "CorrectOption": "Nephelometric Turbidity Units (NTU)",
    "OptionA": "Nephelometric Turbidity Units (NTU)",
    "OptionB": "Degrees Celsius",
    "OptionC": "Milligrams per liter",
    "OptionD": "Meters per second",
    "AnswerExplanation": "Nephelometers quantify light scattering by suspended particles, reported in NTU.",
    "Category": "Field Methods"
  },
  {
    "ID": 12,
    "Question": "Which lake zone is defined by light levels too low for photosynthesis?",
    "CorrectOption": "Aphotic zone",
    "OptionA": "Aphotic zone",
    "OptionB": "Epilimnion",
    "OptionC": "Euphotic zone",
    "OptionD": "Metaliminion",
    "AnswerExplanation": "Below the compensation depth, respiration exceeds photosynthesis, creating an aphotic zone.",
    "Category": "Physical Properties"
  },
  {
    "ID": 13,
    "Question": "During summer stratification, the metalimnion is best described as:",
    "CorrectOption": "Layer with the steepest temperature gradient",
    "OptionA": "Layer with the steepest temperature gradient",
    "OptionB": "Most oxygenated layer",
    "OptionC": "Layer of maximum salinity",
    "OptionD": "Zone of total darkness",
    "AnswerExplanation": "Temperature drops rapidly through this middle layer, separating warm and cold water masses.",
    "Category": "Physical Properties"
  },
  {
    "ID": 14,
    "Question": "Which of the following is an example of a lotic ecosystem?",
    "CorrectOption": "A flowing river",
    "OptionA": "A flowing river",
    "OptionB": "A deep stratified lake",
    "OptionC": "An oxbow pond",
    "OptionD": "A saline playa",
    "AnswerExplanation": "Lotic systems are flowing waters—rivers, streams—where current shapes habitat.",
    "Category": "Introduction"
  },
  {
    "ID": 15,
    "Question": "Oligotrophic lakes typically exhibit which characteristic?",
    "CorrectOption": "High water clarity",
    "OptionA": "High water clarity",
    "OptionB": "Persistent algal blooms",
    "OptionC": "Low dissolved oxygen",
    "OptionD": "Thick organic sediments",
    "AnswerExplanation": "With low nutrients, algal biomass is low and water remains clear.",
    "Category": "Biological Properties"
  },
  {
    "ID": 16,
    "Question": "The volume of water passing a point in a stream per unit time is called:",
    "CorrectOption": "Discharge",
    "OptionA": "Discharge",
    "OptionB": "Baseflow",
    "OptionC": "Infiltration",
    "OptionD": "Evapotranspiration",
    "AnswerExplanation": "Discharge (m³ s⁻¹) integrates velocity across the cross-section.",
    "Category": "Hydrology"
  },
  {
    "ID": 17,
    "Question": "Which parameter directly affects the buoyancy of aquatic organisms?",
    "CorrectOption": "Water density",
    "OptionA": "Water density",
    "OptionB": "Turbidity",
    "OptionC": "Secchi depth",
    "OptionD": "Watershed slope",
    "AnswerExplanation": "Archimedes’ principle: density differences determine flotation versus sinking.",
    "Category": "Physical Properties"
  },
  {
    "ID": 18,
    "Question": "In a lake, the compensation depth is defined where:",
    "CorrectOption": "Photosynthesis equals respiration",
    "OptionA": "Photosynthesis equals respiration",
    "OptionB": "Temperature equals maximum density",
    "OptionC": "Salinity equals atmospheric average",
    "OptionD": "Wind mixing stops",
    "AnswerExplanation": "Net oxygen production is zero; above it autotrophs gain biomass, below they lose it.",
    "Category": "Biological Properties"
  },
  {
    "ID": 19,
    "Question": "Why does cold water hold more dissolved oxygen than warm water?",
    "CorrectOption": "Gas solubility increases as temperature decreases",
    "OptionA": "Gas solubility increases as temperature decreases",
    "OptionB": "Cold water has higher salinity",
    "OptionC": "Cold water forms stronger hydrogen bonds",
    "OptionD": "Turbulence is lower in cold water",
    "AnswerExplanation": "Henry’s law: cooler liquids dissolve gases more readily.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 20,
    "Question": "Which watershed characteristic most strongly influences peak storm runoff?",
    "CorrectOption": "Land slope steepness",
    "OptionA": "Land slope steepness",
    "OptionB": "Average soil pH",
    "OptionC": "Precipitation color",
    "OptionD": "Volume of groundwater springs",
    "AnswerExplanation": "Steep slopes accelerate overland flow, raising peak discharge.",
    "Category": "Watershed"
  },
  {
    "ID": 21,
    "Question": "A meromictic lake is distinguished by:",
    "CorrectOption": "Permanent partial mixing with a non-mixing deep layer",
    "OptionA": "Permanent partial mixing with a non-mixing deep layer",
    "OptionB": "Complete mixing daily",
    "OptionC": "Mixing only during winter",
    "OptionD": "No thermocline formation at all",
    "AnswerExplanation": "Dense, saline bottom water never mixes with upper layers, forming a chemocline.",
    "Category": "Physical Properties"
  },
  {
    "ID": 22,
    "Question": "What term describes the nutrient-enriched water (often at inflow points) that can trigger algal blooms?",
    "CorrectOption": "Eutrophication",
    "OptionA": "Eutrophication",
    "OptionB": "Sedimentation",
    "OptionC": "Desalinization",
    "OptionD": "Calcification",
    "AnswerExplanation": "External nutrient loading accelerates ecosystem aging, termed cultural eutrophication.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 23,
    "Question": "Specific conductance in freshwater is mainly used as a proxy for:",
    "CorrectOption": "Total dissolved ions",
    "OptionA": "Total dissolved ions",
    "OptionB": "Thermal stratification",
    "OptionC": "Chlorophyll-a concentration",
    "OptionD": "Sediment grain size",
    "AnswerExplanation": "Ions carry electric current; higher ion content yields higher conductivity.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 24,
    "Question": "Which of the following is a renewable internal source of phosphorus in lakes?",
    "CorrectOption": "Release from anoxic sediments",
    "OptionA": "Release from anoxic sediments",
    "OptionB": "Atmospheric nitrogen fixation",
    "OptionC": "Acid rain",
    "OptionD": "Wind erosion from deserts",
    "AnswerExplanation": "Low redox in sediments dissolves iron-bound P, recycling it to the water column.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 25,
    "Question": "The volume of water stored in a lake divided by the outflow rate gives the lake’s:",
    "CorrectOption": "Water residence time",
    "OptionA": "Water residence time",
    "OptionB": "Secchi depth",
    "OptionC": "Hydraulic conductivity",
    "OptionD": "Saturation index",
    "AnswerExplanation": "Residence time (turnover time) indicates how long water, nutrients, or pollutants stay.",
    "Category": "Hydrology"
  },
  {
    "ID": 26,
    "Question": "Which physical property of water enables thermal stratification in lakes?",
    "CorrectOption": "Maximum density at 4 °C",
    "OptionA": "Maximum density at 4 °C",
    "OptionB": "High vapor pressure",
    "OptionC": "Low surface tension",
    "OptionD": "Compressibility",
    "AnswerExplanation": "Density decreases both above and below 4 °C, allowing lighter warm and cold layers to float.",
    "Category": "Physical Properties"
  },
  {
    "ID": 27,
    "Question": "Settling velocity of suspended particles in water is increased by:",
    "CorrectOption": "Greater particle diameter",
    "OptionA": "Greater particle diameter",
    "OptionB": "Lower gravity",
    "OptionC": "Higher turbulent flow",
    "OptionD": "Electrostatic repulsion",
    "AnswerExplanation": "Stokes’ law: settling speed rises with the square of particle radius.",
    "Category": "Physical Properties"
  },
  {
    "ID": 28,
    "Question": "Fluorometry is commonly used in limnology for measuring:",
    "CorrectOption": "Chlorophyll-a concentration",
    "OptionA": "Chlorophyll-a concentration",
    "OptionB": "Total hardness",
    "OptionC": "Dissolved potassium",
    "OptionD": "Sediment porosity",
    "AnswerExplanation": "Chlorophyll-a fluoresces; its signal is proportional to algal biomass.",
    "Category": "Field Methods"
  },
  {
    "ID": 29,
    "Question": "A primary function of wetlands in a watershed is to:",
    "CorrectOption": "Attenuate floods by storing water",
    "OptionA": "Attenuate floods by storing water",
    "OptionB": "Increase groundwater salinity",
    "OptionC": "Accelerate urban runoff",
    "OptionD": "Remove all nitrates instantly",
    "AnswerExplanation": "Wetland storage slows runoff peaks, reducing downstream flood risk.",
    "Category": "Watershed"
  },
  {
    "ID": 30,
    "Question": "Which gas exchange process is enhanced by wind-induced surface turbulence?",
    "CorrectOption": "Oxygen diffusion from atmosphere to water",
    "OptionA": "Oxygen diffusion from atmosphere to water",
    "OptionB": "CO₂ respired by sediments",
    "OptionC": "Methane oxidation in deep water",
    "OptionD": "Nitrogen fixation in macrophytes",
    "AnswerExplanation": "Wind increases boundary-layer mixing, boosting O₂ transfer into surface waters.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 31,
    "Question": "Cyanobacteria are often dominant in lakes with:",
    "CorrectOption": "High phosphorus and warm temperatures",
    "OptionA": "High phosphorus and warm temperatures",
    "OptionB": "Low pH and low temperature",
    "OptionC": "High salinity with no nutrients",
    "OptionD": "Very high transparency and cold water",
    "AnswerExplanation": "Cyanobacteria thrive in nutrient-rich, warm, stable conditions and can out-compete other algae.",
    "Category": "Biological Properties"
  },
  {
    "ID": 32,
    "Question": "Which ratio best predicts trophic status: Total Nitrogen to Total Phosphorus (TN:TP) values below __ are considered phosphorus-limited?",
    "CorrectOption": "13:1",
    "OptionA": "13:1",
    "OptionB": "50:1",
    "OptionC": "100:1",
    "OptionD": "200:1",
    "AnswerExplanation": "Below ~13, P is limiting; above ~20, N may limit; Redfield (16) is the classic benchmark.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 33,
    "Question": "The process by which dense, saline water sinks and becomes trapped at a lake bottom is termed:",
    "CorrectOption": "Chemocline formation",
    "OptionA": "Chemocline formation",
    "OptionB": "Evaporation inversion",
    "OptionC": "Seiche oscillation",
    "OptionD": "Dilution plume",
    "AnswerExplanation": "A chemocline separates saline monimolimnion from fresher mixolimnion in meromictic lakes.",
    "Category": "Physical Properties"
  },
  {
    "ID": 34,
    "Question": "Which instrument directly measures water column temperature at multiple depths?",
    "CorrectOption": "Thermistor chain",
    "OptionA": "Thermistor chain",
    "OptionB": "Secchi disk",
    "OptionC": "Hydride generator",
    "OptionD": "Current meter",
    "AnswerExplanation": "A vertical cable of thermistors logs temperature profiles over time.",
    "Category": "Field Methods"
  },
  {
    "ID": 35,
    "Question": "Lake turnover typically occurs in temperate dimictic lakes during:",
    "CorrectOption": "Spring and autumn",
    "OptionA": "Spring and autumn",
    "OptionB": "Mid-summer only",
    "OptionC": "Mid-winter only",
    "OptionD": "Every month",
    "AnswerExplanation": "When surface water cools to 4 °C, density equalizes and wind mixes the whole lake.",
    "Category": "Physical Properties"
  },
  {
    "ID": 36,
    "Question": "Which particle size class settles quickest in calm lake water?",
    "CorrectOption": "Sand (>0.062 mm)",
    "OptionA": "Sand (>0.062 mm)",
    "OptionB": "Silt (0.004-0.062 mm)",
    "OptionC": "Clay (<0.004 mm)",
    "OptionD": "Colloids (<0.001 mm)",
    "AnswerExplanation": "Larger, heavier sand grains experience greater gravitational settling velocity.",
    "Category": "Physical Properties"
  },
  {
    "ID": 37,
    "Question": "Allochthonous organic matter in a lake originates from:",
    "CorrectOption": "Outside the aquatic system (e.g., leaf litter)",
    "OptionA": "Outside the aquatic system (e.g., leaf litter)",
    "OptionB": "Phytoplankton within the lake",
    "OptionC": "Periphyton on sediments",
    "OptionD": "Autochthonous bacteria only",
    "AnswerExplanation": "Allochthonous inputs are external—terrestrial plant debris, soil, etc.",
    "Category": "Biological Properties"
  },
  {
    "ID": 38,
    "Question": "Which physical process can cause internal waves within a stratified lake?",
    "CorrectOption": "Seiche",
    "OptionA": "Seiche",
    "OptionB": "Coriolis effect only",
    "OptionC": "Evaporation",
    "OptionD": "Photosynthesis",
    "AnswerExplanation": "A seiche sloshes water back and forth, tilting the thermocline like a see-saw.",
    "Category": "Physical Properties"
  },
  {
    "ID": 39,
    "Question": "High water color (humic substances) in dystrophic lakes _____ penetration of UV light:",
    "CorrectOption": "Reduces",
    "OptionA": "Reduces",
    "OptionB": "Enhances",
    "OptionC": "Has no effect on",
    "OptionD": "Totally eliminates",
    "AnswerExplanation": "Colored dissolved organic matter strongly absorbs UV and visible light.",
    "Category": "Physical Properties"
  },
  {
    "ID": 40,
    "Question": "The process of nitrogen gas (N₂) conversion into ammonia by cyanobacteria is called:",
    "CorrectOption": "Biological nitrogen fixation",
    "OptionA": "Biological nitrogen fixation",
    "OptionB": "Denitrification",
    "OptionC": "Nitrification",
    "OptionD": "Ammonification",
    "AnswerExplanation": "Nitrogenase enzyme in heterocysts reduces N₂ to NH₃, adding usable N to ecosystems.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 41,
    "Question": "Acidification of lakes can lead to loss of fish populations primarily because:",
    "CorrectOption": "Low pH mobilizes toxic aluminum",
    "OptionA": "Low pH mobilizes toxic aluminum",
    "OptionB": "High alkalinity dissolves oxygen",
    "OptionC": "CO₂ becomes insoluble",
    "OptionD": "Carbonate sediments increase",
    "AnswerExplanation": "Mobilized Al damages fish gills and eggs; pH<5 often critical.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 42,
    "Question": "Residence time in a reservoir is calculated from volume divided by:",
    "CorrectOption": "Outflow rate",
    "OptionA": "Outflow rate",
    "OptionB": "Evaporation rate",
    "OptionC": "Precipitation depth",
    "OptionD": "Catchment area",
    "AnswerExplanation": "It’s an average stay (turnover) time of water mass before leaving the reservoir.",
    "Category": "Hydrology"
  },
  {
    "ID": 43,
    "Question": "Diel vertical migration of zooplankton is thought to be primarily an adaptation to:",
    "CorrectOption": "Avoid visual predators during daylight",
    "OptionA": "Avoid visual predators during daylight",
    "OptionB": "Increase nutrient uptake",
    "OptionC": "Gain oxygen at depth",
    "OptionD": "Conserve body water",
    "AnswerExplanation": "Plankton hide in deep dark water by day, feed near surface at night.",
    "Category": "Biological Properties"
  },
  {
    "ID": 44,
    "Question": "Which form of phosphorus is directly taken up by algae?",
    "CorrectOption": "Orthophosphate (PO₄³⁻)",
    "OptionA": "Orthophosphate (PO₄³⁻)",
    "OptionB": "Particulate organic phosphorus",
    "OptionC": "Polyphosphate chains",
    "OptionD": "Chelated phosphorus",
    "AnswerExplanation": "Algae absorb soluble reactive P, mainly as orthophosphate ions.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 45,
    "Question": "A polymictic lake mixes:",
    "CorrectOption": "Many times per year or continuously",
    "OptionA": "Many times per year or continuously",
    "OptionB": "Only once every decade",
    "OptionC": "Only under ice cover",
    "OptionD": "Never (permanently stratified)",
    "AnswerExplanation": "Shallow tropical or wind-exposed lakes often stratify weakly and mix often.",
    "Category": "Physical Properties"
  },
  {
    "ID": 46,
    "Question": "The rate at which algae produce oxygen in the light minus the oxygen consumed in the dark gives:",
    "CorrectOption": "Net primary productivity",
    "OptionA": "Net primary productivity",
    "OptionB": "Gross primary productivity",
    "OptionC": "Respiration rate",
    "OptionD": "Photosynthetic quotient",
    "AnswerExplanation": "Net = gross photosynthesis minus respiration, measuring biomass gain.",
    "Category": "Biological Properties"
  },
  {
    "ID": 47,
    "Question": "Sediment core dating using ²¹⁰Pb radioisotope typically provides ages up to:",
    "CorrectOption": "About 100-150 years",
    "OptionA": "About 100-150 years",
    "OptionB": "1,000 years",
    "OptionC": "10,000 years",
    "OptionD": "No practical limit",
    "AnswerExplanation": "210Pb half-life (22 yr) is useful for recent sedimentation records ~5-7 half-lives.",
    "Category": "Field Methods"
  },
  {
    "ID": 48,
    "Question": "Macrophytes in littoral zones provide the following benefit:",
    "CorrectOption": "Habitat structure for fish and invertebrates",
    "OptionA": "Habitat structure for fish and invertebrates",
    "OptionB": "Reduction in primary production",
    "OptionC": "Increase in sediment resuspension",
    "OptionD": "Elimination of periphyton",
    "AnswerExplanation": "Physical complexity and refuge among stems enhance biodiversity.",
    "Category": "Biological Properties"
  },
  {
    "ID": 49,
    "Question": "A lake formed by glacial scouring and moraine dams is called a:",
    "CorrectOption": "Glacial lake",
    "OptionA": "Glacial lake",
    "OptionB": "Tectonic lake",
    "OptionC": "Volcanic caldera lake",
    "OptionD": "Solution lake",
    "AnswerExplanation": "Most northern temperate lakes owe their basins to glacial erosion/deposition.",
    "Category": "Formation"
  },
  {
    "ID": 50,
    "Question": "Which equation estimates theoretical evaporation under ideal conditions?",
    "CorrectOption": "Dalton’s law of evaporation",
    "OptionA": "Dalton’s law of evaporation",
    "OptionB": "Henry’s law",
    "OptionC": "Fick’s law",
    "OptionD": "Beer–Lambert law",
    "AnswerExplanation": "Dalton related evaporation rate to vapor pressure deficit and wind speed.",
    "Category": "Hydrology"
  },
  {
    "ID": 51,
    "Question": "Heterotrophic bacteria in lakes play a critical role in:",
    "CorrectOption": "Decomposition of organic matter",
    "OptionA": "Decomposition of organic matter",
    "OptionB": "Fixing atmospheric nitrogen only",
    "OptionC": "Reducing heavy metals to solids",
    "OptionD": "Generating internal seiches",
    "AnswerExplanation": "They mineralize organic carbon, recycling nutrients back into the food web.",
    "Category": "Biological Properties"
  },
  {
    "ID": 52,
    "Question": "Which sensor would you use to continuously record surface irradiance at a lake?",
    "CorrectOption": "Pyranometer",
    "OptionA": "Pyranometer",
    "OptionB": "Fluorometer",
    "OptionC": "Refractometer",
    "OptionD": "Secchi disk",
    "AnswerExplanation": "A pyranometer measures total solar radiation flux density (W m⁻²).",
    "Category": "Field Methods"
  },
  {
    "ID": 53,
    "Question": "An increase in alkalinity generally indicates a greater capacity to:",
    "CorrectOption": "Buffer pH changes",
    "OptionA": "Buffer pH changes",
    "OptionB": "Lower conductivity",
    "OptionC": "Increase turbidity",
    "OptionD": "Accelerate stratification",
    "AnswerExplanation": "Bicarbonate and carbonate ions neutralize acids, stabilizing pH.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 54,
    "Question": "Which isotopic ratio is widely used to study groundwater-lake interactions?",
    "CorrectOption": "⁸⁷Sr/⁸⁶Sr",
    "OptionA": "⁸⁷Sr/⁸⁶Sr",
    "OptionB": "¹⁴C/¹²C",
    "OptionC": "²⁰⁶Pb/²⁰⁴Pb",
    "OptionD": "³H/³He",
    "AnswerExplanation": "Different rock types impart distinctive Sr signatures to groundwater entering lakes.",
    "Category": "Hydrology"
  },
  {
    "ID": 55,
    "Question": "The 'Allometry' concept in plankton ecology relates cell size to:",
    "CorrectOption": "Physiological rates such as growth or respiration",
    "OptionA": "Physiological rates such as growth or respiration",
    "OptionB": "Streamflow velocity",
    "OptionC": "Watershed slope",
    "OptionD": "Dissolved silica",
    "AnswerExplanation": "Metabolic rate scales predictably with organism size via allometric equations.",
    "Category": "Biological Properties"
  },
  {
    "ID": 56,
    "Question": "A river reach with alternating deep pools and shallow riffles is best described as:",
    "CorrectOption": "Pool-riffle sequence",
    "OptionA": "Pool-riffle sequence",
    "OptionB": "Braided channel",
    "OptionC": "Straight thalweg",
    "OptionD": "Dendritic drainage",
    "AnswerExplanation": "Pool-riffle morphology is common in gravel-bed streams and enhances habitat diversity.",
    "Category": "Hydrology"
  },
  {
    "ID": 57,
    "Question": "Which of the following reduces the likelihood of algal blooms?",
    "CorrectOption": "Reducing nutrient inputs (P and N)",
    "OptionA": "Reducing nutrient inputs (P and N)",
    "OptionB": "Increasing sediment resuspension",
    "OptionC": "Adding fish predators",
    "OptionD": "Lowering water clarity",
    "AnswerExplanation": "Cutting external nutrient sources is the primary control on excessive algal growth.",
    "Category": "Management"
  },
  {
    "ID": 58,
    "Question": "The primary pigment used by algae for photosynthesis is:",
    "CorrectOption": "Chlorophyll-a",
    "OptionA": "Chlorophyll-a",
    "OptionB": "Xanthophyll",
    "OptionC": "Phycocyanin",
    "OptionD": "Carotene",
    "AnswerExplanation": "Chlorophyll-a absorbs red/blue light, driving light reactions of photosynthesis.",
    "Category": "Biological Properties"
  },
  {
    "ID": 59,
    "Question": "Which hydrologic process returns the largest volume of water back to the atmosphere from land?",
    "CorrectOption": "Evapotranspiration",
    "OptionA": "Evapotranspiration",
    "OptionB": "Infiltration",
    "OptionC": "Runoff",
    "OptionD": "Percolation",
    "AnswerExplanation": "Combined evaporation and plant transpiration dominate terrestrial water loss.",
    "Category": "Hydrology"
  },
  {
    "ID": 60,
    "Question": "Which method is commonly used to estimate gross primary production in lakes via oxygen changes?",
    "CorrectOption": "Light-and-dark bottle method",
    "OptionA": "Light-and-dark bottle method",
    "OptionB": "Secchi depth attenuation",
    "OptionC": "Evaporation pan",
    "OptionD": "Gravimetric filtration",
    "AnswerExplanation": "O₂ produced in light minus O₂ in dark bottles yields gross and net production.",
    "Category": "Field Methods"
  },
  {
    "ID": 61,
    "Question": "Large woody debris in streams generally:",
    "CorrectOption": "Creates habitat complexity and slows flow",
    "OptionA": "Creates habitat complexity and slows flow",
    "OptionB": "Eliminates hyporheic exchange",
    "OptionC": "Reduces dissolved oxygen",
    "OptionD": "Increases water temperature",
    "AnswerExplanation": "Logs form pools, trap sediment, and provide cover for aquatic life.",
    "Category": "Hydrology"
  },
  {
    "ID": 62,
    "Question": "The term 'metalimnetic oxygen maximum' refers to elevated DO at the thermocline due to:",
    "CorrectOption": "Photosynthesis by phytoplankton concentrated at that depth",
    "OptionA": "Photosynthesis by phytoplankton concentrated at that depth",
    "OptionB": "Groundwater upwelling",
    "OptionC": "Oxygen from sediments diffusing upward",
    "OptionD": "Gas supersaturation from ice melt",
    "AnswerExplanation": "Algae accumulate at the light-nutrient balance depth, producing excess O₂.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 63,
    "Question": "Photic depth often defined as 1% surface light is roughly equal to _____ times secchi depth in clear lakes.",
    "CorrectOption": "2.5-3",
    "OptionA": "2.5-3",
    "OptionB": "1",
    "OptionC": "5-6",
    "OptionD": "10",
    "AnswerExplanation": "Empirical studies show euphotic depth ≈ 2.7× Secchi in low-color waters.",
    "Category": "Physical Properties"
  },
  {
    "ID": 64,
    "Question": "The Coriolis effect causes large lake currents in the Northern Hemisphere to deflect:",
    "CorrectOption": "To the right of the wind direction",
    "OptionA": "To the right of the wind direction",
    "OptionB": "To the left of the wind direction",
    "OptionC": "Straight downward",
    "OptionD": "Has no effect on lakes",
    "AnswerExplanation": "Earth’s rotation deflects moving water rightward north of the equator.",
    "Category": "Physical Properties"
  },
  {
    "ID": 65,
    "Question": "Biomanipulation to control algal blooms often involves stocking:",
    "CorrectOption": "Piscivorous fish to reduce planktivores",
    "OptionA": "Piscivorous fish to reduce planktivores",
    "OptionB": "Herbivorous fish to graze macrophytes",
    "OptionC": "Benthic feeders to stir sediments",
    "OptionD": "Mosquito larvae to consume algae",
    "AnswerExplanation": "Top-down control: fewer planktivores → more zooplankton grazers → less algae.",
    "Category": "Management"
  },
  {
    "ID": 66,
    "Question": "Which of the following best describes bankfull discharge?",
    "CorrectOption": "Flow that fills the channel and just begins to spill onto the floodplain",
    "OptionA": "Flow that fills the channel and just begins to spill onto the floodplain",
    "OptionB": "Lowest flow in a 10-year drought",
    "OptionC": "Discharge during the 100-year flood",
    "OptionD": "Flow velocity at the thalweg",
    "AnswerExplanation": "Geomorphically effective flow shaping the channel occurs near bankfull.",
    "Category": "Hydrology"
  },
  {
    "ID": 67,
    "Question": "Littoral zones often have higher biodiversity because of:",
    "CorrectOption": "Structural complexity from macrophytes",
    "OptionA": "Structural complexity from macrophytes",
    "OptionB": "Low light and low oxygen",
    "OptionC": "An absence of predators",
    "OptionD": "Lower nutrient levels",
    "AnswerExplanation": "Vegetation, substrate diversity, and light create many niches for organisms.",
    "Category": "Biological Properties"
  },
  {
    "ID": 68,
    "Question": "Which component of the hydrologic cycle directly contributes to groundwater recharge?",
    "CorrectOption": "Infiltration through soil",
    "OptionA": "Infiltration through soil",
    "OptionB": "Canopy interception",
    "OptionC": "Evapotranspiration",
    "OptionD": "Surface runoff",
    "AnswerExplanation": "Water percolates downward, replenishing aquifers that later feed springs.",
    "Category": "Hydrology"
  },
  {
    "ID": 69,
    "Question": "Reduced mixing due to strong thermal stratification can lead to hypolimnetic:",
    "CorrectOption": "Oxygen depletion",
    "OptionA": "Oxygen depletion",
    "OptionB": "High transparency",
    "OptionC": "Temperature increase",
    "OptionD": "Phytoplankton blooms",
    "AnswerExplanation": "Isolation from atmosphere and respiration of settling organics consume O₂.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 70,
    "Question": "Which of the following best explains a seiche event?",
    "CorrectOption": "Standing oscillation of lake water caused by wind or pressure changes",
    "OptionA": "Standing oscillation of lake water caused by wind or pressure changes",
    "OptionB": "Vibrations in sediments from earthquakes",
    "OptionC": "Ice sheet expansion and contraction",
    "OptionD": "Internal production of methane bubbles",
    "AnswerExplanation": "Wind pushes water to one side; when wind stops, the water sloshes back and forth.",
    "Category": "Physical Properties"
  },
  {
    "ID": 71,
    "Question": "The Redfield ratio of 106:16:1 refers to the atomic ratio of:",
    "CorrectOption": "C:N:P in phytoplankton",
    "OptionA": "C:N:P in phytoplankton",
    "OptionB": "Na:K:Mg in seawater",
    "OptionC": "Fe:Mn:Cu in sediments",
    "OptionD": "H:O:Si in diatoms",
    "AnswerExplanation": "Marine and freshwater plankton average these elemental proportions in biomass.",
    "Category": "Biological Properties"
  },
  {
    "ID": 72,
    "Question": "A lake with high electrical conductivity likely indicates:",
    "CorrectOption": "High concentration of dissolved ions",
    "OptionA": "High concentration of dissolved ions",
    "OptionB": "Low nutrient status",
    "OptionC": "High dissolved oxygen",
    "OptionD": "Low total dissolved solids",
    "AnswerExplanation": "Conductivity is directly proportional to ionic strength of the water.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 73,
    "Question": "Which equation is used to model light attenuation with depth in water?",
    "CorrectOption": "Beer–Lambert law",
    "OptionA": "Beer–Lambert law",
    "OptionB": "Stokes law",
    "OptionC": "Reynolds number",
    "OptionD": "Poiseuille equation",
    "AnswerExplanation": "Light intensity decreases exponentially: I(z)=I₀e^(-kz).",
    "Category": "Physical Properties"
  },
  {
    "ID": 74,
    "Question": "Which macronutrient element is essential for ATP and DNA in aquatic organisms?",
    "CorrectOption": "Phosphorus",
    "OptionA": "Phosphorus",
    "OptionB": "Chloride",
    "OptionC": "Sulfate",
    "OptionD": "Argon",
    "AnswerExplanation": "Phosphorus forms the backbone of ATP, DNA, and phospholipids.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 75,
    "Question": "Calcite precipitation (whiting events) in lakes typically occurs when:",
    "CorrectOption": "Photosynthesis raises pH and causes CaCO₃ to precipitate",
    "OptionA": "Photosynthesis raises pH and causes CaCO₃ to precipitate",
    "OptionB": "Respiration lowers pH and dissolves CaCO₃",
    "OptionC": "CO₂ is injected into water",
    "OptionD": "Sulfur bacteria oxidize pyrite",
    "AnswerExplanation": "Removal of CO₂ during photosynthesis shifts carbonate equilibrium, precipitating CaCO₃.",
    "Category": "Chemical Properties"
  },
  {
    "ID": 76,
    "Question": "Invasive zebra mussels often alter lake ecosystems by:",
    "CorrectOption": "Increasing water clarity through filter feeding",
    "OptionA": "Increasing water clarity through filter feeding",
    "OptionB": "Producing cyanotoxins",
    "OptionC": "Raising water temperature",
    "OptionD": "Decreasing calcium concentration",
    "AnswerExplanation": "They remove particles, clearing water, which can shift algal and macrophyte dynamics.",
    "Category": "Biological Properties"
  },
  {
    "ID": 77,
    "Question": "A stream reach dominated by fine sediments and low gradient likely supports which habitat type?",
    "CorrectOption": "Sand-bed glide habitat",
    "OptionA": "Sand-bed glide habitat",
    "OptionB": "Cobble riffle habitat",
    "OptionC": "Bedrock cascade",
    "OptionD": "Boulder rapid",
    "AnswerExplanation": "Low slope streams deposit sand, forming slow glides rather than riffles.",
    "Category": "Hydrology"
  },
  {
    "ID": 78,
    "Question": "Which lake measurement technique directly estimates total primary production under natural light?",
    "CorrectOption": "Diurnal dissolved-oxygen curve method",
    "OptionA": "Diurnal dissolved-oxygen curve method",
    "OptionB": "Light-dark bottle incubation only",
    "OptionC": "Secchi depth conversion",
    "OptionD": "GIS shoreline mapping",
    "AnswerExplanation": "Tracking whole-lake O₂ change over 24 h integrates photosynthesis and respiration.",
    "Category": "Field Methods"
  },
  {
    "ID": 79,
    "Question": "The ratio of lake shoreline length to the circumference of a circle with equal area is called:",
    "CorrectOption": "Shoreline development index",
    "OptionA": "Shoreline development index",
    "OptionB": "Fetch ratio",
    "OptionC": "Volume development index",
    "OptionD": "Secchi coefficient",
    "AnswerExplanation": "This index indicates shoreline complexity; higher values mean more irregular shore.",
    "Category": "Physical Properties"
  },
  {
    "ID": 80,
    "Question": "Which of the following actions best mitigates cultural eutrophication?",
    "CorrectOption": "Reducing phosphorus inputs from wastewater",
    "OptionA": "Reducing phosphorus inputs from wastewater",
    "OptionB": "Increasing dredging frequency",
    "OptionC": "Lowering lake level each spring",
    "OptionD": "Adding urea-N fertilizer to stimulate algae",
    "AnswerExplanation": "Cutting point-source P is the most effective, long-term eutrophication control.",
    "Category": "Management"
  }
]

       
        